### ISSUE TITLE
Linkcollider Error

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#10]
I am getting Points for the first 20 minutes of running script with errors but then the points stop earning. Please check the below Error.
![image](https://user-images.githubusercontent.com/85780689/199695302-455a4b82-a546-46f9-a4dd-96492e12d8c9.png)

**Comment by asimptot** [comment]
Hi @saabtech ,

Do you change loop cycle more than 20? If so, don't change. Because Linkcollider allows to earn point to surf video in 20 cycles.

**Comment by saabtech** [comment]
> Hi @saabtech ,
> 
> Do you change loop cycle more than 20? If so, don't change. Because Linkcollider allows to earn point to surf video in 20 cycles.

I havent changed anything in script xcept adding username /mail and password.

**Comment by asimptot** [comment]
@saabtech hi,

I have a doubt about Linkcollider website. Because even if you get more points, you can't use them to get followers. If you verify that it works fine, i can try to fix your issue. Otherwise, it's not gonna work!

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I have a doubt about Linkcollider website. Because even if you get more points, you can't use them to get followers. If you verify that it works fine, i can try to fix your issue. Otherwise, it's not gonna work!

You are right, tried to use earned point but i did not see any increase in followers .

**Comment by asimptot** [comment]
@saabtech hi,

So, I close the issue. If you find effective website to gain follower, please let me know and focus on this. Btw, YouLikeHits works fine to gain Twitter likes and retweets!

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> So, I close the issue. If you find effective website to gain follower, please let me know and focus on this. Btw, YouLikeHits works fine to gain Twitter likes and retweets!

Ya, it works great
