### ISSUE TITLE
Kingdomlike Error 

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#11]
The KingdomLike script works for a while and stop by providing errors as below:

![image](https://user-images.githubusercontent.com/85780689/200778150-98afb32d-3938-4a06-8bcf-ebd558d13c7f.png)

**Comment by asimptot** [comment]
@saabtech hi,

When it doesn't find a website to surf or a video to watch, it gives this error.

**Comment by asimptot** [comment]
I can add control but even if I add it, it won't any content to surf or watch. When you get the error, you can stop to run it.

**Comment by saabtech** [comment]
> I can add control but even if I add it, it won't any content to surf or watch. When you get the error, you can stop to run it.

I suggest if the script restart or refresh every 20 minute and auto run again will be great, same goes for youhitlike

**Comment by asimptot** [comment]
I have just updated the code. You can use the latest one.
