### ISSUE TITLE
Enhancement:  Script for Tiktok Followers, Likes 

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#12]
Is it possible to create the script for Tiktok Followers, Likes etc just like for Instagram followers and like?

**Comment by asimptot** [comment]
@saabtech hi,

In order to test it, can you give your TikTok username and post link, please? Because I don't have any account and I don't want to create an account.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> In order to test it, can you give your TikTok username and post link, please? Because I don't have any account and I don't want to create an account.

Please find the account username: https://www.tiktok.com/@mr__nobodii

Post Link: https://www.tiktok.com/@mr__nobodii/video/7077667951150697729

**Comment by asimptot** [comment]
@saabtech hi,

Have you ever used in the following links? If yes, let me know. Because it says no credits left.

https://tolinay.com/tiktok-takipci-hilesi
https://tolinay.com/tiktok-begeni-hilesi

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Have you ever used in the following links? If yes, let me know. Because it says no credits left.
> 
> https://tolinay.com/tiktok-takipci-hilesi https://tolinay.com/tiktok-begeni-hilesi

No i havent used it. 

Try below :

User link:  https://www.tiktok.com/@noriplacas

Video Link: https://www.tiktok.com/@noriplacas/video/7161337076481346821

**Comment by asimptot** [comment]
@saabtech hi,

Tolinay that we used as bot on Instagram doesn't let us send more request. So we need to find alternative websites.
