### ISSUE TITLE
Enhancement: Creating Scripts for Tiktok

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#13]
Probably you have come across the website  https://zefoy.com/ 

By solving the capture manually, you can get Likes, followers, views etc. there are some scripts in Github but they are not working well.

I hope if you can look into this website and come up with a good script.

**Comment by asimptot** [comment]
@saabtech hi,

How does the program work? Even I couldn't log in the system.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/18220180/200939001-b7ed8190-8727-4ced-bb22-e9164f9d52d5.png">

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> How does the program work? Even I couldn't log in the system.
> 
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/18220180/200939001-b7ed8190-8727-4ced-bb22-e9164f9d52d5.png">

It doesnt need any login, We just need to manually add the captcha once every 15 to 20 minutes and we get all the boost from the tasks available, most of the time each task will be under maintenance. there are some bots out here but they dont work cuz they are outdated.

**Comment by asimptot** [comment]
@saabtech hi,

What application can we use on zefoy? Tiktok, Instagram, Twitter? I just try to understand how it works! Btw, it includes human verification control in the beginning of the page.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> What application can we use on zefoy? Tiktok, Instagram, Twitter? I just try to understand how it works! Btw, it includes human verification control in the beginning of the page.

Zefoy only provide Tiktok services, Yes the human verification appear at the beginning and we need to manually solve that, after that the page loads with services. Some scripts are already there on Github about zefoy.

**Comment by asimptot** [comment]
@saabtech hi,

Yes, but most of clients and developers want to have a website to run it fully automatically. So I don't want to develop on Zefoy.
