### ISSUE TITLE
Error on YouHitLike

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#14]
I am getting this error and the script shut down

![image](https://user-images.githubusercontent.com/85780689/201089926-d05c551e-56d4-4517-bb11-e99f7affa057.png)

**Comment by asimptot** [comment]
@saabtech hi,

When you have no content to watch a video or to surf website, it will return the error.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> When you have no content to watch a video or to surf website, it will return the error.

But the script crash and closes. Is there a work around where the script refresh every 5 to 10 minutes without crashing?

**Comment by asimptot** [comment]
@saabtech  hi,

Okay, let me try to fix it.

**Comment by asimptot** [comment]
@saabtech hi,

I've just updated the code. You can test it on your side. Since I had no problem before, I couldn't test it.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I've just updated the code. You can test it on your side. Since I had no problem before, I couldn't test it.

I will check it now, thanks

**Comment by asimptot** [comment]
@saabtech hi,

I have updated again. If you get error watching videos on Youtube, the code will start to surf websites.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I have updated again. If you get error watching videos on Youtube, the code will start to surf websites.

The sprevious script works great, but the idea of adding website should work wonder. Thanks alot mate.

**Comment by asimptot** [comment]
@saabtech hi,

But when there is no website on surfing part, it will return an error. If you find good alternative websites, let me know! :)

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> But when there is no website on surfing part, it will return an error. If you find good alternative websites, let me know! :)

If the website has nothing to surf, will the script move to youtube views and vice-versa?

**Comment by asimptot** [comment]
@saabtech hi,

Normally it should work but i don't know how to edit the code. Let me fix on my side and inform you.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Normally it should work but i don't know how to edit the code. Let me fix on my side and inform you.

will the script crash when there is no websurf or YT view? cuz it crash with me after running it for long time

**Comment by asimptot** [comment]
@saabtech hi,

Unfortunatelly yes, because when there are no websites or no videos, the program can't run, well.
