### ISSUE TITLE
YoulikeHit scrip Crashes

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#15]
The script crashes after couple of minutes. I ran the script for 22 minutes and it crashed. Please see the screenshot below for the activities the script performed and crashed, it seems the script doesnt shuffle to websurf.

![image](https://user-images.githubusercontent.com/85780689/201471014-fb456a55-6c84-4b48-839f-de2f43ccce3a.png)

**Comment by asimptot** [comment]
@saabtech hi,

I used TABS to surf websites. Can you run the program after you do in the following steps?

* Find init.py file.
* Add # in front of chrome_options.add_argument('--headless')
* It should be #chrome_options.add_argument('--headless') and run your program again.

I want to see the error on the browser.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I used TABS to surf websites. I have just added keyword controls. Can you use up-to-date init.py file and get_credit_on_YouLikeHits.py, please?

I used the latest script and ran it for hours and saw the activities in Youlikehit , after viewing YT and shifting to Web surf, the script completed all tasks, I got this error in IDLE.

Getting credits... Please do not terminate the program.
Traceback (most recent call last):
  File "E:\Hacking\Social Media Scripts\FollowerBot-main\get_credit_on_YouLikeHits.py", line 29, in go_to_website
    yt_view = self.browser.find_element(By.XPATH, '//*[@id="listall"]/center/a[1]')
  File "C:\Users\Android\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Android\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Android\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="listall"]/center/a[1]"}
  (Session info: headless chrome=107.0.5304.107)
Stacktrace:
Backtrace:
	Ordinal0 [0x00EAACD3+2075859]
	Ordinal0 [0x00E3EE61+1633889]
	Ordinal0 [0x00D3B7BD+571325]
	Ordinal0 [0x00D6AC2F+764975]
	Ordinal0 [0x00D6AE1B+765467]
	Ordinal0 [0x00D9D0F2+970994]
	Ordinal0 [0x00D87364+881508]
	Ordinal0 [0x00D9B56A+963946]
	Ordinal0 [0x00D87136+880950]
	Ordinal0 [0x00D5FEFD+720637]
	Ordinal0 [0x00D60F3F+724799]
	GetHandleVerifier [0x0115EED2+2769538]
	GetHandleVerifier [0x01150D95+2711877]
	GetHandleVerifier [0x00F3A03A+521194]
	GetHandleVerifier [0x00F38DA0+516432]
	Ordinal0 [0x00E4682C+1665068]
	Ordinal0 [0x00E4B128+1683752]
	Ordinal0 [0x00E4B215+1683989]
	Ordinal0 [0x00E56484+1729668]
	BaseThreadInitThunk [0x756CFEF9+25]
	RtlGetAppContainerNamedObjectPath [0x775C7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x775C7B8E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Hacking\Social Media Scripts\FollowerBot-main\get_credit_on_YouLikeHits.py", line 49, in <module>
    ylh.go_to_website()
  File "E:\Hacking\Social Media Scripts\FollowerBot-main\get_credit_on_YouLikeHits.py", line 36, in go_to_website
    surf = WebDriverWait(self.browser, 10).until(
  File "C:\Users\Android\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00EAACD3+2075859]
	Ordinal0 [0x00E3EE61+1633889]
	Ordinal0 [0x00D3B7BD+571325]
	Ordinal0 [0x00D6AC2F+764975]
	Ordinal0 [0x00D6AE1B+765467]
	Ordinal0 [0x00D9D0F2+970994]
	Ordinal0 [0x00D87364+881508]
	Ordinal0 [0x00D9B56A+963946]
	Ordinal0 [0x00D87136+880950]
	Ordinal0 [0x00D5FEFD+720637]
	Ordinal0 [0x00D60F3F+724799]
	GetHandleVerifier [0x0115EED2+2769538]
	GetHandleVerifier [0x01150D95+2711877]
	GetHandleVerifier [0x00F3A03A+521194]
	GetHandleVerifier [0x00F38DA0+516432]
	Ordinal0 [0x00E4682C+1665068]
	Ordinal0 [0x00E4B128+1683752]
	Ordinal0 [0x00E4B215+1683989]
	Ordinal0 [0x00E56484+1729668]
	BaseThreadInitThunk [0x756CFEF9+25]
	RtlGetAppContainerNamedObjectPath [0x775C7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x775C7B8E+238]

**Comment by asimptot** [comment]
@saabtech hi,

I committed the program and it will run infinitely and no need tabs. If it doesn't find a video, it will surf websites. If it doesn't find websites, it will close and re-run again in loop.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I committed the program and it will run infinitely and no need tabs. If it doesn't find a video, it will surf websites. If it doesn't find websites, it will close and re-run again in loop.

The script works great so far, After completing all tasks and when there is nothing left within the website, the script gives " handshake failed " error and the script restart the loop. Good Job Mate.

**Comment by asimptot** [comment]
@saabtech hi,

Good to know. May I close the issue?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Good to know. May I close the issue?

Yes You can. Please see the below script actions performed.

![image](https://user-images.githubusercontent.com/85780689/201604287-d25e1373-4fbd-485e-9fd3-bd4c28960f66.png)
