### ISSUE TITLE
Adding "NopeCHA: CAPTCHA Solver" to the browser

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#16]
Is it possible to include the NopeCHA: CAPTCHA Solver from chrome web store, since this addon will be able to bypass / Solve any captcha. ( Free users 100 Captcha daily )
This way You can create script for addmefast and Like4like etc since they are using CAPTCHA system.

Link for addon: https://nopecha.com/

**Comment by asimptot** [comment]
@saabtech hi,

I had had a problem with addmefast that they detect i am bot. I don't know how I will pass the screen. If you want, I can write a basic program to show you.

Like4Like.org checks the character and they don't use Google CAPTCHA. So we can't fix the issue. If you have a website that uses CAPTCHA, let me know.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I had had a problem with addmefast that they detect i am bot. I don't know how I will pass the screen. If you want, I can write a basic program to show you.
> 
> Like4Like.org checks the character and they don't use Google CAPTCHA. So we can't fix the issue. If you have a website that uses CAPTCHA, let me know.

I use paid Dimension BOT  ( https://dimensionbots.com/ ) they have built in captcha bypass Addon. The Bot pretty much does everything automated tasks for addmefast and other sites.

**Comment by asimptot** [comment]
@saabtech hi,

Please use the bot and give your feedback. While you're watching videos on Youtube, if you see the bot control, please change it manually. I can't pass them and you shouldn't run the program in headless mode due to bot controls of Addmefast. You should skip bot steps manually.

https://github.com/asimptot/FollowerBot/blob/main/get_credit_on_AddMeFast.py

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Please use the bot and give your feedback. While you're watching videos on Youtube, if you see the bot control, please change it manually. I can't pass them and you shouldn't run the program in headless mode due to bot controls of Addmefast. You should skip bot steps manually.
> 
> https://github.com/asimptot/FollowerBot/blob/main/get_credit_on_AddMeFast.py

The Script works good with website surfs, but quite difficult to convince YT views due to captcha, Is it possible to just add websurf and loop it just like you created YouHitLike script.

**Comment by asimptot** [comment]
@saabtech hi,

Actually i wrote the script like YouLikeHits. Because if it can't find website to surf, it watches videos on Youtube. If you don't like to watch videos on YouTube, i will remove it.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Actually i wrote the script like YouLikeHits. Because if it can't find website to surf, it watches videos on Youtube. If you don't like to watch videos on YouTube, i will remove it.

Kindly only make it to run website and loop it forever in case if there is no website task to perform. I will make a dummy account for addmefast to run it n see if there is any security issues arises while running the script for 24 hours.

**Comment by asimptot** [comment]
@saabtech hi,

Lol, when I tried to run just surfing website, AddMeFast blocked me. Do we need to set timer for each website?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Lol, when I tried to run just surfing website, AddMeFast blocked me. Do we need to set timer for each website?

No wonder why i created a dummy account :P The dimension BOT as I use it with Addmefast never get detected and there is a timer in it, between 4 to 5 seconds between closing and opening each task. A sleep cooldown of 30 seconds after each websurf will be better.

**Comment by asimptot** [comment]
@saabtech hi,

I have better idea in this issue. When we have no website to surf, we'll wait a long time. The algorithm will generate a number between 1-300 seconds. Probably, they won't know who we're bot.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I have better idea in this issue. When we have no website to surf, we'll wait a long time. The algorithm will generate a number between 1-300 seconds. Probably, they won't know who we're bot.

The same method i have seen with one of the Instagram Automation BOT , where it sleep randomely from 100 to 500 seconds.... I can test the script for a long run cuz i got dummy accounts with me for testing

**Comment by asimptot** [comment]
@saabtech hi,

I have added controls that I mentioned. Re-run and give your feedback.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I have added controls that I mentioned. Re-run and give your feedback.

The script works great, I have been lucky so far, the website surf works great too.

**Comment by asimptot** [comment]
@saabtech hi,

I'll close the issue as fixed.
