### ISSUE TITLE
Addmefast  Script Modification Tasks

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#17]
I tried the new Addmefast script which include instagram tasks and Twitter Tasks. Sounds great.

 - YT views Task can be removed since it will always ask for Captcha Solve.

  - Twitter Followers probably the account will get suspended dude to spam following. The safest way will be keeping twitter likes since    they have no limit per day and adding Tweet as well as  retweet task. ( Tweet and retweet altogether limit is 1,000  per day. )
 
 - Instagram follower and Like Task should be safer by margin since we get only temporary block which is lifted within 24 hours.
 
 - Please if you can add All Facebook Tasks since they are safe to use and we only get temporary ban which can be lifted within 24 hours.
 
 - Twich Followers task can be added as it is safe too. The only issue is we have to add the login verification code sent to our gmail. If you can have a look around through script which as for verification of twich then we can add it manually.
 
 - Reverbnation Fans Task is safe too to be included.
 
 
 Running the Script at the moment , I am not getting points. Please see the error below from screenshot.

![image](https://user-images.githubusercontent.com/85780689/203733437-0fbec241-87de-4085-8c5b-9c425c88ecec.png)

**Comment by saabtech** [comment]
Please check the screenshot below, not sure if the bot is detected our script is going faster with tasks. The twitter follow and LIke works but with every task end, I get error

![image](https://user-images.githubusercontent.com/85780689/203738122-1ba4ba77-1c70-44e6-944a-e4be4e0d7cd9.png)

**Comment by asimptot** [comment]
@saabtech hi,

Thanks for your remarks.

1) YoutubeView --> I won't remove it, because some users use the function manually. Is it possible to skip Captcha Control using extension?
2) Facebook --> Okay, I will add ASAP. Since I don't have FB account, I didn't write functions.
3) Twitch --> Please use the function on Addmefast manually. Even I can't earn point using Twitch function manually.
4) Reverbnation Fans --> Please try to earn point manually. If there is less content, it will be unneccessary to add.
5) Instagram --> I have trouble problems in like function. One of them is Addmefast side. Because it shows us contents that I've already liked. So when I click like button, it dislikes the content and I can't earn point. Other problem is about like function. Some contents can't be liked due to having different XPATH, CLASS_NAME etc. I'm not sure how I can write it generic. I will focus on this.
6) Timeout --> Normally, if all tasks return 'no item', it passes to next one. Shall I add timer for all tasks? For example: When all twitter_like contents are over, the program can wait a long time.
7) Your problem --> I don't know, let me check on my side.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Thanks for your remarks.
> 
>     1. YoutubeView --> I won't remove it, because some users use the function manually. Is it possible to skip Captcha Control using extension?
> 
>     2. Facebook --> Okay, I will add ASAP. Since I don't have FB account, I didn't write functions.
> 
>     3. Twitch --> Please use the function on Addmefast manually. Even I can't earn point using Twitch function manually.
> 
>     4. Reverbnation Fans --> Please try to earn point manually. If there is less content, it will be unneccessary to add.
> 
>     5. Instagram --> I have trouble problems in like function. One of them is Addmefast side. Because it shows us contents that I've already liked. So when I click like button, it dislikes the content and I can't earn point. Other problem is about like function. Some contents can't be liked due to having different XPATH, CLASS_NAME etc. I'm not sure how I can write it generic. I will focus on this.
> 
>     6. Timeout --> Normally, if all tasks return 'no item', it passes to next one. Shall I add timer for all tasks? For example: When all twitter_like contents are over, the program can wait a long time.
> 
>     7. Your problem --> I don't know, let me check on my side.

Point 1 : there are couple of extension based on AI they solve the captcha. Nopecha and Buster captcha but they have daily free limit.

Point 2 : I can provide you with dummy FB account but due to IP change it will be detected as suspicious attempt and probably get locked or disabled. 

Point 3. Noted.

Point 4 : Noted

Point 5 : Probably due to shadow ban from insta for liking too many post / videos, shadow ban go away within 24 hours.

Point 6 : when all Tasks are completed for specific platform, its advisable to go for a cooldown time like 3 to 10 minutes randomly. that way more tasks are generated in AMF and script looks safer too.

Ponint 7: I will run the script for long hours to see the safety of it.

**Comment by asimptot** [comment]
@saabtech hi,

2) I will focus on FB task. Don't share on here.
5) How many post should be liked on Instagram daily? Is 20 post okay?
6) I changed but didn't test it due to access problem to Addmefast. Waiting for fixing the issue.

**Comment by saabtech** [comment]
Point 3 : Instagram Daily Likes 200 to 300 Per day limit

**Comment by saabtech** [comment]
There is still something confusing either with website or script, that doesnt credit the points. I ran the script for 20 hours and collected 200 points. see the screenshot below: 

![image](https://user-images.githubusercontent.com/85780689/203910185-744e1387-b5a7-44c3-b712-c4b6cc7bc0bc.png)

**Comment by asimptot** [comment]
Have you ever checked your Twitter account? Sometimes Twitter asks whether you're bot or not. I got the same problem yesterday. After I passed human verification, it continued to collect points. Btw, you don't have to stop running the program while you're verifying.

**Comment by saabtech** [comment]
> Have you ever checked your Twitter account? Sometimes Twitter asks whether you're bot or not. I got the same problem yesterday. After I passed human verification, it continued to collect points. Btw, you don't have to stop running the program while you're verifying.

I will try that and let you know. thanks

**Comment by asimptot** [comment]
@saabtech hi,

What about random task choice? We have retweet, twitter like, follow, instagram like, web surfing, yt view. If we choose them randomly, does it make collecting points easy?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> What about random task choice? We have retweet, twitter like, follow, instagram like, web surfing, yt view. If we choose them randomly, does it make collecting points easy?

Not sure, I have played around with some BOTs from other GitHubers and they have something called m" move to new task after completing random 3 to 5 task"

**Comment by asimptot** [comment]
Okay, unless it helps us gain more point, i won't add it, thanks! I have trouble finding Facebook Like web element values. I hope I will fix it soon!

**Comment by saabtech** [comment]
> Okay, unless it helps us gain more point, i won't add it, thanks! I have trouble finding Facebook Like web element values. I hope I will fix it soon!

I am stuck at the same points, despite the task does follow for twitter. The earning points does not increase.

![image](https://user-images.githubusercontent.com/85780689/203936383-1c635ccb-7b64-4f66-9858-a945393f2906.png)

**Comment by asimptot** [comment]
@saabtech hi,

Can you share screeshots in non-headless mode, please?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Can you share screeshots in non-headless mode, please?

Ive noticed one thing, When the script run in non-headless, I pretty much get points from all task, but when it is in headless mode, the point never change.

**Comment by asimptot** [comment]
Strange! It works on my side... If it's possible, please try using different Twitter account. Btw, I have added Facebook tasks.

**Comment by saabtech** [comment]
> 



> Strange! It works on my side... If it's possible, please try using different Twitter account. Btw, I have added Facebook tasks.

thats allright, I will run the script with non-Head. I will try the new script now.

**Comment by saabtech** [comment]
facebook  all tasks included?

**Comment by saabtech** [comment]
> Strange! It works on my side... If it's possible, please try using different Twitter account. Btw, I have added Facebook tasks.

I tried the new script, when the script succesfully log in to addmefast, The facebook login creates issue, by opening another tab of Meta Secure pay, and login to facebook in first tab, due to which instagram login is also affected. Look the screenshot below:

![image](https://user-images.githubusercontent.com/85780689/203979495-e39c5103-4d32-4cb8-b077-ff97af0792a6.png)

**Comment by asimptot** [comment]
@saabtech hi,

Does it occur while you're accepting cookies on Facebook and Instagram?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Does it occur while you're accepting cookies on Facebook and Instagram?

I do nothing, I just let the script run.

**Comment by asimptot** [comment]
I fixed the issue for Instagram and Facebook login. You can use the latest one.

**Comment by saabtech** [comment]
> I fixed the issue for Instagram and Facebook login. You can use the latest one.

I tried the new script of addmefast, The facebook login is creating issue for me. Not logging in and the script stops.

![image](https://user-images.githubusercontent.com/85780689/204074936-b35fd640-f019-4ca2-9296-b7b4d130fd35.png)

**Comment by asimptot** [comment]
@saabtech hi,

Can you share your ss in non headless mode?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Can you share your ss in non headless mode?

I tried but the browser just close itself and no username or password is added by the script to the FB login page hence the browser closes and i get the above error as seen in screenshot previously. Does it run with you ?

**Comment by asimptot** [comment]
@saabtech hi,

Yes, it works! You can change tab values as the fancy takes you while logging in Facebook. It seems Facebook shows different ui to you.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Yes, it works! You can change tab values as the fancy takes you while logging in Facebook. It seems Facebook shows different ui to you.

Not sure how to do that i am not good at that.

**Comment by asimptot** [comment]
@saabtech hi,

Open facebook login page and see cookies page. Press tabs continously and tell me how many tabs that you used when you go to accept button.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Open facebook login page and see cookies page. Press tabs continously and tell me how many tabs that you used when you go to accept button.

Well am sorry, I am not good at such things at all :'( If only i knew

**Comment by asimptot** [comment]
@saabtech hi,

No, that is not program side. Please apply in the following steps manually.

1) Open your browser in private mode.
2) Go to facebook.com
3) See cookies acceptance page.
4) Press tab until you find the acceptance button.
5) Tell me how many tabs that you used.

**Comment by saabtech** [comment]
> 4\. ess tab until you find the acceptance button.

I opened facebook.com on incognito Mode, but i did not get any cookies acceptance page.

**Comment by asimptot** [comment]
@saabtech hi,

1) Go to get_credit_on_AddMeFast.py program.
2) Go to 11st row and change sleep(4) as sleep(444).
3) Run program again.
4) Enter facebook.com manually.
5) See cookies page and find how many tabs are required.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
>     1. Go to get_credit_on_AddMeFast.py program.
> 
>     2. Go to 11st row and change sleep(4) as sleep(444).
> 
>     3. Run program again.
> 
>     4. Enter facebook.com manually.
> 
>     5. See cookies page and find how many tabs are required.

Do i need to click on cookies on lower page of facebook page or i should be expecting a cookies page to open. Cuz i followed what you mentioned. but i dont get the point No.5 .... sorry i am not much familiar with these stuffs.

**Comment by asimptot** [comment]
@saabtech hi,

Please apply 5th step as the following video:    https://we.tl/t-u3H87u7A9F

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Please apply 5th step as the following video: https://we.tl/t-u3H87u7A9F

I dont know turkish, The page i see inj video does not appear to me anywere when i type facebook.com manually. CAn you access my PC via teamviwer ? I will share the ID / Pass via email. If you can

**Comment by asimptot** [comment]
@saabtech hi,

Yes, I can. Sorry for Turkish, I just tried to explain how you can go to the approve button via tabs. Count how many tabs that you used until the approve button.

**Comment by saabtech** [comment]
please send test email to : shimjitsu@gmail.com so i can share with you teamviwer cuz i tried several times but i failed.

**Comment by saabtech** [comment]
I have found couple of things in the addmefast script, The script says " we could not find content to collect points, waiting 400 seconds"

But when i check manually and logging to addmefast, I do find the content on twitter Instagram, Facebook and reddit, 

does the script collect points from single task say like if it want to collect points from twitter likes, will the script wait there and refresh so it can find new task in twitter Likes page or move to new platform say Instagram likes in case if nothing is found in twitter likes and so one. because the waiting time is longer than it earns.
Please find the screenshot below:

![image](https://user-images.githubusercontent.com/85780689/204231867-6587568a-da3a-4d20-b935-24407ce12fc6.png)


Soundcloud can be included in script since it does not require any verification.

**Comment by asimptot** [comment]
@saabtech hi,

I know this issue. When you used Twitter follow or retweet tasks manually, Addmefast doesn't give point to you. This problem are based on Addmefast side. Sometimes, if you like, retweet or follow more on Twitter, Twitter restricts those operations. While the program is running, check your Twitter account manually.

**Comment by asimptot** [comment]
@saabtech hi,

I'm closing this issue. For new problems, please open a new ticket.
