### ISSUE TITLE
Shuffle Tasks : addmefast Script

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#18]
Is it possible to shuffle the tasks for each platform ( instagram, twitter, FB, YT, PT, Reddit etc ) every 3 minutes because the script keeps waiting to earn points .

![image](https://user-images.githubusercontent.com/85780689/204522680-7486f64e-5b11-41ca-801c-ac93d1ac4cb1.png)

after the waiting time, does the script move to another Task? or stay within the same platform.

**Comment by asimptot** [comment]
@saabtech hi,

Yes, you should use in the following code block.

array = [amf.twitter_like, amf.twitter_retweet, amf.twitter_follow,
             amf.reddit_members, amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers,
              amf.instagram_like, amf.instagram_follow, amf.facebook_followers, amf.facebook_share]

while(True):
    try:
        choice(array)()
    except:
        print('We could not find a content to collect points. We are waiting 180 seconds...')
        sleep(180)


Instead of this:

array = [amf.surf_website, amf.youtube_view, amf.twitter_like, amf.twitter_retweet, amf.twitter_follow,
            amf.instagram_like, amf.instagram_follow, amf.facebook_followers, amf.facebook_share, 
            amf.reddit_members, amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers]

while(True):
    try:
        choice(array)()
    except:
        delay = randint(100, 300)
        print('We could not find a content to collect points. We are waiting ' + str(delay) + ' seconds...')
        sleep(delay)

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Yes, you should use in the following code block.
> 
> array = [amf.twitter_like, amf.twitter_retweet, amf.twitter_follow, amf.reddit_members, amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers, amf.instagram_like, amf.instagram_follow, amf.facebook_followers, amf.facebook_share]
> 
> while(True): try: choice(array)() except: print('We could not find a content to collect points. We are waiting 180 seconds...') sleep(180)
> 
> Instead of this:
> 
> array = [amf.surf_website, amf.youtube_view, amf.twitter_like, amf.twitter_retweet, amf.twitter_follow, amf.instagram_like, amf.instagram_follow, amf.facebook_followers, amf.facebook_share, amf.reddit_members, amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers]
> 
> while(True): try: choice(array)() except: delay = randint(100, 300) print('We could not find a content to collect points. We are waiting ' + str(delay) + ' seconds...') sleep(delay)

![image](https://user-images.githubusercontent.com/85780689/204533608-460f33a0-479f-40e1-bfa1-dbad2e747ff2.png)

It is still the same. works for like two to three tasks and then all it does is not finding points to earn.

**Comment by asimptot** [comment]
@saabtech hi,

If current tasks have no content, you will get this message. Because it searches for follow/like/subscribe button.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> If current tasks have no content, you will get this message. Because it searches for follow/like/subscribe button.

It wouldnt jump to another tasks? like if twitter has no follow/likes/retweet tasks, will the script not skip and start earning points from FB or YT etc?

**Comment by asimptot** [comment]
@saabtech hi,

Normally, it was working like you mentioned. However, I changed it 3-4 days ago and now it chooses tasks randomly. So Twitter, Facebook or any platform don't block us. You can change your sleep value from 180 to less value.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Normally, it was working like you mentioned. However, I changed it 3-4 days ago and now it chooses tasks randomly. So Twitter, Facebook or any platform don't block us. You can change your sleep value from 180 to less value.

is there non headless mode as i tried as its not working with me when changed the value of #headless

**Comment by asimptot** [comment]
I didnt understand what you mean. Did you use the latest init file?

**Comment by saabtech** [comment]
> I didnt understand what you mean. Did you use the latest init file?

I can confirm one thing, in headless mode all accounts are logged in but we wont get points. In nonheadless mode, we get points.

**Comment by asimptot** [comment]
@saabtech hi,

Can you add this code block in every login task? For example:

    def login_gmail(self):
        self.browser.get('https://mail.google.com')
        sleep(5)

        actions = ActionChains(self.browser)
        actions.send_keys(YOUR GMAIL ADDRESS).perform()
        sleep(2)
        actions.send_keys(Keys.RETURN).perform()
        sleep(2)

        actions.send_keys(YOUR GMAIL PASSWORD).perform()
        sleep(2)
        actions.send_keys(Keys.RETURN).perform()

        sleep(10)
        if "Inbox" in self.browser.page_source:
            print('Logged in Gmail.')
        else:
            print('Something went wrong in Gmail login process.')
            **self.browser.save_screenshot('gmail.png)**

For other task, please name as task name like 'pinteres.png, instagram.png'

After you run, please show me your ss.

**Comment by saabtech** [comment]
> 

![image](https://user-images.githubusercontent.com/85780689/204797705-542d7155-682c-47b2-8c0e-acbf87b5a61c.png)

Afer adding the above block, I get this error running the script

**Comment by asimptot** [comment]
@saabtech hi,

You should add in the following. Since it's in bold type, you look like copying * chars :)

self.browser.save_screenshot('gmail'.png)

**Comment by saabtech** [comment]
I am running it in non headless mode and the script earn points pretty well.
