### ISSUE TITLE
YouLikeHits Script : Long YT Videos

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#19]
I have come across one tiny issue, and that is when YT has long video like 1 hour to 3 hours, they should be either skipped or provide limited time to view. suppose a video with 3 hours  should be viewed only for 2-3 minutes because the video keep playing for hours and doesnt move to other tasks. Please check from your end incase if the same happen from your side as well.

**Comment by asimptot** [comment]
@saabtech hi,

Timer has been 130 seconds while watching video. Do you mean that some videos have been more than 130 seconds? If so, let me know and work on this.

**Comment by asimptot** [comment]
@saabtech hi,

I fixed the issue. Please use the latest code.
