### ISSUE TITLE
Trial has ended

### ISSUE THREAD

**Issue by EdenEitani** [asimptot/FollowerBot#2]
Hi, 
I'm getting this error. 
I've managed to gain 400 followers in 2 days of operation.
(your description says I should get 1000+ followers a day, and it seems impossible)
Please let me know how to resolve this. Thank you for your work.
<img width="795" alt="Screen Shot 2022-10-13 at 10 26 46" src="https://user-images.githubusercontent.com/16803684/195533136-43bf5041-7657-46ca-ab74-4ee85bc3aea4.png">

**Comment by asimptot** [comment]
Hi @EdenEitani ,

This issue has been jusr resolved. Please try to run up to date code on your side.

**Comment by EdenEitani** [comment]
Hi @asimptot 
How should one add an Instagram account?
there is no Instagram option there.

**Comment by asimptot** [comment]
Hi @EdenEitani ,

Use this link --> https://www.youlikehits.com/addinstagram.php

**Comment by EdenEitani** [comment]
Okay... So now if the credits to tolinay are expired we're getting credits in the second website - but I don't see any follow action after gaining credits there. Just looping through youtube videos views.

**Comment by asimptot** [comment]
Correct! While you are collecting credits on the 2nd website, you will get followers in progress of time. Before you run the program, you need to add your accout to the system manually. Please set 30 points before running the program. Per follow request to you, you will lose 30 points. But the program will get points while wathcing YT videos in the background :)

**Comment by asimptot** [comment]
@EdenEitani hi,

Btw, if you change your Instagram username, the first website works well! They don't check your id on Instagram system. If you need to get more followers, change your username in per 400 followers.
