### ISSUE TITLE
consistent error when running all the bots for sites

### ISSUE THREAD

**Issue by Rjaycc** [asimptot/FollowerBot#21]
C:\Users\rjxmw\Desktop\FollowerBot-main>python get_credit_on_YouLikeHits.py
  File "C:\Users\rjxmw\Desktop\FollowerBot-main\get_credit_on_YouLikeHits.py", line 15
    uid.send_keys(YOUR YOULIKEHITS USERNAME)
                  ^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

C:\Users\rjxmw\Desktop\FollowerBot-main>

anyone know a fix?

**Comment by saabtech** [comment]
i am sure you havent added your login username and password to the script. 

replace (YOUR YOULIKEHITS USERNAME) with your username. and the same for password as well.

**Comment by Rjaycc** [comment]
> i am sure you havent added your login username and password to the script.
> 
> replace (YOUR YOULIKEHITS USERNAME) with your username. and the same for password as well.

I have.... same error

**Comment by Rjaycc** [comment]
![Screenshot 2022-12-06 000603](https://user-images.githubusercontent.com/112223729/205844129-4c524b03-4ac9-43ef-92a3-14887a62edf5.png)
i removed my password but yes I added it check it out

**Comment by Rjaycc** [comment]
![Screenshot 2022-12-06 000933](https://user-images.githubusercontent.com/112223729/205844724-d9e6c7b0-0f21-40bf-baeb-530cb713c013.png)
Now it doesnt do anything...

**Comment by Rjaycc** [comment]
Found the solution, " " were missing in one of the command lines , have no idea how it was removed but it was (:👍
