### ISSUE TITLE
YouLikeHits Script issue

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#22]
I used the latest script and it seems after viewing videos for an hour, the script somehow show no error and yet still does not earn any point.
screenshot below: 

![image](https://user-images.githubusercontent.com/85780689/205847576-dbd5b131-dcaa-4ce0-9ea5-ff32d5f012f9.png)

**Comment by saabtech** [comment]
After closing the script and restarting over, the script start earning points. seems like an issue somewhere with script i guess.

**Comment by saabtech** [comment]
@asimptot it seems like the script doesnt earn any point after 30 to 40 min. I checked manually in the website the tasks are available. but the script doesnt earn. I am running the script for almost 4 hours and doesnt earn points.

**Comment by saabtech** [comment]
Yes, i added but when i check the YT activities and Web Surf activites, The script wont earn after 40 minutes every single time. I tried running and restarting the script multiple times, this is what happens the script stop earning after 40 min. 

Good, You can check from your end.

**Comment by saabtech** [comment]
> Let me test on my side. Can you try to re-run after you remove the page, please?

I will try to remove the pages and run the script n let you know the performance of it.

**Comment by asimptot** [comment]
@saabtech hi,

As a tester, I reproduced this issue. I'm trying to figure out this.

**Comment by saabtech** [comment]
Noted, also is it normal for script to open so many process of chrome?

Please see the below snapshot, I also noticed when script is closed, some process of chrome are left out.

![image](https://user-images.githubusercontent.com/85780689/205883331-b15533b2-d255-476b-aee1-52e240a86df5.png)

**Comment by asimptot** [comment]
@saabtech hi,

Of course no! Does it work the same in other scripts such as AddmeFast ?

**Comment by asimptot** [comment]
Please use the latest code. I fixed it and it works on my side.

**Comment by saabtech** [comment]
> Please use the latest code. I fixed it and it works on my side.

I will try it now
