### ISSUE TITLE
YouLikeHits Script 

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#24]
@asimptot  hi,

The new script create multiple chromedriver process : screenshot below: 

![image](https://user-images.githubusercontent.com/85780689/206153555-0cf291cd-71a2-4e2f-b8e9-049df52c4de9.png)

Also, there are numerous google chrome process that utilize the whole RAM and hand the system.

![image](https://user-images.githubusercontent.com/85780689/206154130-2a96dd97-4cd9-4f12-8b5f-e952fda8ae2e.png)

Please assist.

**Comment by asimptot** [comment]
Yes, because when it clicked website contents, it was opened a new tab.

**Comment by saabtech** [comment]
> Yes, because when it clicked website contents, it was opened a new tab.

is it possible when the script restart, it closes all the tabs, so the RAM is not consumed since it keep increasing till the system.

**Comment by saabtech** [comment]
I tried nonheadless mode and found that when the script try to reloop from the beginning. It wont close the browser but instead open a new browser and start login in and continue earning points. Hence everytime the script complete cycle it leave behind the browser and make new one. See the screenshot below:

![image](https://user-images.githubusercontent.com/85780689/206162408-ceddbb5f-181d-4e52-bf24-1dc2d715c19a.png)

**Comment by asimptot** [comment]
@saabtech hi,

As I understand the issue has been resolved but it causes a side effect issue. Please use the latest one. It won't create new session.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> As I understand the issue has been resolved but it causes a side effect issue. Please use the latest one. It won't create new session.

I will give it a long run to see the impact. Thank asim, appreciate your quick response and resolving the issues.
