### ISSUE TITLE
Can you add ktechseven 

### ISSUE THREAD

**Issue by rehxnnq** [asimptot/FollowerBot#25]
Can you add ktechseven "https://ktechseven.com/" please, it does not have any human verification.

**Comment by asimptot** [comment]
@rehxnnq hi,

I will deal with it, but website surf doesn't work on my side. Does it work on your side?

**Comment by rehxnnq** [comment]
yes it is working on my side

**Comment by asimptot** [comment]
Fixed --> https://github.com/asimptot/FollowerBot/blob/main/get_credit_on_KtechSeven.py

**Comment by asimptot** [comment]
@rehxnnq if you give a star, i'll be glad :)
