### ISSUE TITLE
Adding Captcha extension to the browser

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#27]
Hi @asim

Will it be possible to add the extension for captcha resolver to the browser that way we can skip the captcha login for example for Like4Like which is one of the top social media growing sites. If that is possible then Like4Like script will be a fantastic script to earn points through automation.

**Comment by asimptot** [comment]
@saabtech hi,

What kind of extension is it? I can't develop a unique captcha app, but I can try to add a captcha app to browser. Please share its name with me.

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> What kind of extension is it? I can't develop a unique captcha app, but I can try to add a captcha app to browser. Please share its name with me.

https://chrome.google.com/webstore/detail/nopecha-captcha-solver/dknlfmjaanfblgfdfebhijalfmhmjjjo

**Comment by asimptot** [comment]
I see 2 LikeforLike websites. Which one do you use?

1) https://www.like4like.org/
2) https://like4like.com/

**Comment by saabtech** [comment]
> I see 2 LikeforLike websites. Which one do you use?
> 
>     1. https://www.like4like.org/
> 
>     2. https://like4like.com/

https://www.like4like.org/

**Comment by asimptot** [comment]
<img width="251" alt="Screenshot 2022-12-30 095538" src="https://user-images.githubusercontent.com/18220180/210052521-d2cc656d-760c-4b67-8aba-4b660823a333.png">

I wasn't able to use this extension. I got in the following IP warning message. How can I use it?

**Comment by saabtech** [comment]
> <img alt="Screenshot 2022-12-30 095538" width="251" src="https://user-images.githubusercontent.com/18220180/210052521-d2cc656d-760c-4b67-8aba-4b660823a333.png">
> 
> I wasn't able to use this extension. I got in the following IP warning message. How can I use it?

it seems like some countries are unable to use it, but we do get 100 credits free per day which solves 95% of the captch automatically. Can you change your IP and try again.

**Comment by asimptot** [comment]
@saabtech hi,

Although I used Hotspot Shield Free VPN, it didn't work on my side :(

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Although I used Hotspot Shield Free VPN, it didn't work on my side :(

try protonvpn, Hotspot shield is not a good vpn at all.

**Comment by asimptot** [comment]
@saabtech hi,

Sorry but the extension returns the same error using Proton VPN as well. My business computer might be blocking...

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Sorry but the extension returns the same error using Proton VPN as well. My business computer might be blocking...

probably VPN restriction.
