### ISSUE TITLE
Follower code doesn't working 

### ISSUE THREAD

**Issue by TEDDY6969** [asimptot/FollowerBot#28]
Hey, so i am trying to run this code on replit as i am broke to have a pc lol. But i am facing this error. Can someone help me out please 
![Uploading Screenshot_2023-01-03-20-37-36-32.png…]()

**Comment by asimptot** [comment]
@TEDDY6969 hi,

Sorry, but I can't see the image that you shared. Can you share it again?

**Comment by TEDDY6969** [comment]
> @TEDDY6969 hi,
> 
> Sorry, but I can't see the image that you shared. Can you share it again?

Ya for sure here it is
![Uploading Screenshot_2023-01-03-20-37-36-32.png…]()
Umm idk what's wrong here if you are unable to view the image please consider checking it out on 
https://timecapsule.jatinsharma24.repl.co/uploads/Screenshot_2023-01-03-20-37-26-96_cbf47468f7ecfbd8ebcc46bf9cc626da.png

**Comment by asimptot** [comment]
@TEDDY6969 hi,

Can you run the code in non headless mode, please? In order to run, please add # to 15th raw in init.py. When you see the error, share your browser's image.

#chrome_options.add_argument('--headless')

**Comment by TEDDY6969** [comment]
> @TEDDY6969 hi,
> 
> Can you run the code in non headless mode, please? In order to run, please add # to 15th raw in init.py. When you see the error, share your browser's image.
> 
> #chrome_options.add_argument('--headless')

Bro, I tried to do so but still getting that same kind of error. I ran it without headless 
And i got following error:-
![Screenshot_2023-01-04-07-21-46-58](https://user-images.githubusercontent.com/75193966/210470429-472079a7-caa5-4c69-bdd2-29702ef8c2d4.png)
![Screenshot_2023-01-04-07-22-14-59](https://user-images.githubusercontent.com/75193966/210470425-632a5735-7123-4989-b743-fbc3456f541c.png)

**Comment by asimptot** [comment]
@TEDDY6969 hi,

Are you sure that you ran the correct program? I see you have tried to run instafollow.py file in the logs.

**Comment by TEDDY6969** [comment]
Ya bro, I am running the correct file only I have just changed its name as get_insta_follower is too long to write in console for me XD. So python instafollow.py

**Comment by asimptot** [comment]
Oh okay. Then, you should have this path in your setup: C:\Projects\Get_Free_Followers   . And your instafollow.py and init.py scripts should be in the folder. Do you use the latest code in the system, now?

**Comment by TEDDY6969** [comment]
@asimptot ya bro, infact i just clone the code last night so it's so fresh. Bro, if the code working for you can you clone it and give it to me umm can you try it if it works for you?

**Comment by asimptot** [comment]
@TEDDY6969 hi,

I'm not sure that you have used the same code. Because your log includes subprocess library and I never used it. Please do in the following steps.

1) Go to https://github.com/asimptot/FollowerBot/blob/main/get_instagram_followers.py.
2) Copy all lines.
3) Run again.

**Comment by TEDDY6969** [comment]
@asimptot Hey, I clone it again and ran it again but still encountered the same error. These are the recent logs
![IMG_20230104_192102](https://user-images.githubusercontent.com/75193966/210569911-e3187eb0-ccab-4b05-8334-7e5cfd8ad584.jpg)
![IMG_20230104_192119](https://user-images.githubusercontent.com/75193966/210569949-867f3a1e-644c-4425-a930-898065c10387.jpg)

**Comment by TEDDY6969** [comment]
@asimptot hey, actually i am not on pc. I am using replit. I can invite you in the project. If it works for you. https://replit.com this is the website maybe you can create an account and then I'll share my project link okay?

**Comment by TEDDY6969** [comment]
@asimptot hey thanks alot buddy! Here's the link to my project:- https://replit.com/join/lxrvshdkgy-iiiv

**Comment by asimptot** [comment]
@TEDDY6969 hi,

Where should I start the program? If you try to run in on Replit, it won't work. Because you should define paths locally and run on your side. You got this error, because the program can't find init.py.

**Comment by TEDDY6969** [comment]
Ohh, umm mate! Can you tell me on which line and file i need to make corrections? And to run the code in shell write python get_insta_followers.py. well just make the corrections I'll run it. Does it works?

**Comment by asimptot** [comment]
Please make sure you installed Python in your computer.

1) Go to C:\Projects\Get_Free_Followers in your local pc. If you don't have folder, create using the same name.
2) Open CMD prompt and write cd C:\Projects\Get_Free_Followers.
3) Write 'python get_instagram_followers.py' then press enter.

**Comment by TEDDY6969** [comment]
@asimptot bro the problem is i don't have a computer can't this work without it. Is there any other method?

**Comment by asimptot** [comment]
@TEDDY6969 hi,

Sorry, but I have no clue on this :( this program has been designed to work on PC.

**Comment by asimptot** [comment]
@TEDDY6969  good luck man! :)
