### ISSUE TITLE
Error with bot

### ISSUE THREAD

**Issue by JustLele78** [asimptot/FollowerBot#31]
Hi, I have this error that has been appearing since today, yesterday the bot was working, could you help me?
![error](https://user-images.githubusercontent.com/86966093/211875658-e8823835-817a-4d17-ac48-00dd7dfe107c.PNG)

**Comment by asimptot** [comment]
Hi,

Please update 15th line as self.browser = uc.Chrome(options=chrome_options, version_main=109) in init.py. If it works, let me know.

**Comment by asimptot** [comment]
Please write 107 instead of 109, now. If it doesn't work, I have an alternative solution, too!

**Comment by JustLele78** [comment]
now it works thank you :3
