### ISSUE TITLE
Bot error

### ISSUE THREAD

**Issue by JustLele78** [asimptot/FollowerBot#34]
Hi again, it worked for a while, but it gave me the same error again, what can I do?
![errrror](https://user-images.githubusercontent.com/86966093/212412750-f5ee9fb5-86bb-4eed-8785-3fb016381b51.PNG)

**Comment by asimptot** [comment]
Strange! Did you change your line as _self.browser = uc.Chrome(options=chrome_options, version_main=107_ ??

**Comment by JustLele78** [comment]
Sure, like you told me the other day

**Comment by JustLele78** [comment]
Hey, are you there?

**Comment by asimptot** [comment]
@JustLele78 hi,

Please update your init.py file as the following. 

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class Setup:
    def init(self):
        warnings.filterwarnings("ignore")
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--window-size=1036, 674')
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option('useAutomationExtension', False)
        chrome_options.add_argument('--headless')
        chrome_options.add_argument("--log-level=3")
        chrome_options.add_experimental_option("prefs", {
            "profile.default_content_setting_values.notifications": 1
        })
        self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )

    def close_browser(self):
        self.browser.close()

**Comment by JustLele78** [comment]
I replaced the code and now it works, thank you!
