### ISSUE TITLE
Addmefast error

### ISSUE THREAD

**Issue by sbironx** [asimptot/FollowerBot#37]
Hi, i have this error, can you help me please?
![addmefast error](https://user-images.githubusercontent.com/122805854/212706831-b4bbb73a-2858-4d12-9feb-9fa3686da9ca.PNG)

**Comment by asimptot** [comment]
@sbironx hi,

Please run it in non headless mode and share your ss with me.

**Comment by sbironx** [comment]
Hi, to start it in non-headless mode is done like this right ? `#chrome_options.add_argument('--headless')` 
and what is ss?

**Comment by asimptot** [comment]
Yes,
ss means screenshot. Please take a capture.

**Comment by asimptot** [comment]
I want to see your browser's screenshot, not terminal. Please share your browser's ss.

**Comment by sbironx** [comment]
yes, I enter the credentials here
![error4](https://user-images.githubusercontent.com/122805854/212733586-9534f59b-c1cf-4777-8fcf-ceb278761704.PNG)

**Comment by asimptot** [comment]
I reproduced the issue. It's about human verification control. Please log in Reverbnation on Chrome manually for one time. After you verify your login process, when you run the program, it won't show human verification control to you, again.

**Comment by sbironx** [comment]
> Reverbnation
