### ISSUE TITLE
YouhitLike Error : Invalid decimal Literal

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#4]
I tried the Youhitlike but I get decimal Literal error in line 21 pwd.send_keys

The script doesnt execute because of the above error. I have added all the information within the script ( username and password ) 

Let me know if I am missing something.

**Comment by asimptot** [comment]
@saabtech hi,

Did you try to run up to date script, right? --> https://github.com/asimptot/FollowerBot/blob/main/get_credit_on_YouLikeHits.py

If yes, please put # char to 19th raw in init.py file and share your screenshot of your browser and terminal message.

**Comment by saabtech** [comment]
thank you for the quick reply, Yes, I am trying upto date script. The script does not run when I double click. It wont open. tried the suggestion you provided #char to 19th within init.py and still the script wont open.

**Comment by asimptot** [comment]
Could you share your raw that you entered username and password, please? I just want to know the format is true or not. You can blur your username and password. Please share your full error message on terminal.

**Comment by saabtech** [comment]
Please find the below :

![image](https://user-images.githubusercontent.com/85780689/196926470-91e42c54-a47e-4766-a1af-6c49bcd4d616.png)

![image](https://user-images.githubusercontent.com/85780689/196926718-9067795a-8c61-455e-b121-9a3fae4027f2.png)

**Comment by asimptot** [comment]
Strange! Do you use your password like this format, right? It should be between ' chars for example: 
   pwd.send_keys('1234abcd123ABC*')

**Comment by saabtech** [comment]
> Strange! Do you use your password like this format, right? It should be between ' chars for example: pwd.send_keys('1234abcd123ABC*')

After adding commas to each side of the password and username it is working now... Thanks
