### ISSUE TITLE
No module named 'selenium'

### ISSUE THREAD

**Issue by fabus961** [asimptot/FollowerBot#42]
**OS:** 
Win10

**Python Version:** 
pip22.3.1, python 3.10

**Describe the error**
I ran pip3 install -r requirements.txt without error. 
When executing init.py or get_instagram_followers.py I get the below output

**Message ouput**
init.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Assumptions**
I guess it's a windows related problem, will test on macOS and Ubuntu asap!

**Comment by asimptot** [comment]
It seems you didn't install selenium library on your Linux or macOS environment. Please make sure you install libraries. This problem is caused by your setup.

**Comment by fabus961** [comment]
Do you use Windows? If so which python / pip version?

Tested **Win10 22H2 19045.2486** and **WSL Ubuntu 22.04.1 LTS** (pip22.3.1, python 3.10). Both don't seem to work for my setup. I already checked the library installation as provided in your README.md and named in my error description. Installation process is running through without any errors.

**macOS Ventura 13.1** with pip 21.2.4 and python 3.9.6 does the job properly 🥳

Testing **Ubuntu 22.10** is going to follow up soon, I'll let you know 🚀

**Comment by asimptot** [comment]
@fabus961 hi,

Python:    V3.10.5
Pip:           V22.3.1

I'm waiting for your feedback!

**Comment by fabus961** [comment]
Ubuntu (pip 22.0.2/python 3.10) operates well... I will wipe pip/python from my win10 and try again to make sure there are no conflicts with potential older versions. 

Thx @asimptot!
