### ISSUE TITLE
An error has been occurred. Retrying...

### ISSUE THREAD

**Issue by DEAD404ERROR** [asimptot/FollowerBot#44]
installed all the required packages, the error just goes repeating

**Comment by asimptot** [comment]
@DEAD404ERROR hi,

What kind of error did you get?

**Comment by DEAD404ERROR** [comment]
![image](https://user-images.githubusercontent.com/84570159/216109649-b15d9e2a-0525-4770-93bd-b5b268e1a6e4.png)
I this get error in get_instagram_like.py and get_instagram_followers.py never tried on others

**Comment by asimptot** [comment]
Can you please run the code in non headless mode? I'd like to see your browser behavior.

**Comment by DEAD404ERROR** [comment]
> Can you please run the code in non headless mode? I'd like to see your browser behavior.

How do to tht ?

**Comment by asimptot** [comment]
Please add '#' char to 14th line in the https://github.com/asimptot/FollowerBot/blob/main/init.py
then start to run

**Comment by DEAD404ERROR** [comment]
![image](https://user-images.githubusercontent.com/84570159/216626631-9282f595-de3b-4292-a1e5-39b2ffda2357.png)

**Comment by DEAD404ERROR** [comment]
![image](https://user-images.githubusercontent.com/84570159/216627396-3d5eabbb-60d0-4c5d-abf6-40f6de3405b3.png)
Getting this error in chrome canary

**Comment by DEAD404ERROR** [comment]
![image](https://user-images.githubusercontent.com/84570159/216627753-7b0e23a1-0065-48df-9788-f19d4d114409.png)
Getting this error in chrome canary

**Comment by DEAD404ERROR** [comment]
ok
