### ISSUE TITLE
i get error!

### ISSUE THREAD

**Issue by wieczorek-kamil** [asimptot/FollowerBot#46]
Hello!

PS C:\Users\Kamil\Desktop\FollowerBot-main> python get_instagram_likes.py
Traceback (most recent call last):
  File "C:\Users\Kamil\Desktop\FollowerBot-main\get_instagram_likes.py", line 4, in <module>
    from init import *
  File "C:\Users\Kamil\Desktop\FollowerBot-main\init.py", line 12
    def init(self):
    ^
IndentationError: expected an indented block after class definition on line 11

 please update your init file as the following.

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class Setup:
def init(self):
warnings.filterwarnings("ignore")
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--window-size=1036, 674')
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option('useAutomationExtension', False)
chrome_options.add_argument('--headless')
chrome_options.add_argument("--log-level=3")
chrome_options.add_experimental_option("prefs", {
"profile.default_content_setting_values.notifications": 1
})
self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )

def close_browser(self):
self.browser.close()

i update this init file but still not working. how fix this ?

**Comment by asimptot** [comment]
You should add tabs at the beginning of the lines. Please see the format in the screenshot.
<img width="469" alt="Screenshot 2023-02-03 083808" src="https://user-images.githubusercontent.com/18220180/216540638-748589bd-45e8-4d20-9a27-16f55fb64a8b.png">

**Comment by asimptot** [comment]
Please compare your code and the image. 

<img width="475" alt="image" src="https://user-images.githubusercontent.com/18220180/216541379-0cfc3bb4-a531-4ed4-96c0-7fe93069ecf9.png">

**Comment by asimptot** [comment]
It seems you didn't add tabs, please add them. Otherwise, Python doesn't allow to run the program on your setup.

**Comment by asimptot** [comment]
Here, you can find --> https://github.com/asimptot/FollowerBot/blob/main/init.py

Please don't copy the code. Because while you're copying, you forget to paste tabs. Just download the file and run on your local.

**Comment by asimptot** [comment]
Strange! Please keep running the code 1 hour and share your ss and logs with me. Maybe you'll see some activities later.

**Comment by asimptot** [comment]
You should check Python tutorial videos. Sorry but it seems the problem was caused by your local.
