### ISSUE TITLE
not getting followers

### ISSUE THREAD

**Issue by diipda** [asimptot/FollowerBot#47]
hi i am a huge fan of ur channel and i hope u reply so when i use the follwers script sometimes i get the 10 followers and most of the time i dont

**Comment by asimptot** [comment]
@diipda hi,

I guess this is the server problem. Did you try to boost any alternative account?

**Comment by diipda** [comment]
Hi thank you for your response
I think the issue was that when I leave my Instagram open I don't get the
followers and when I close it I do and thank you for your help and for your
amazing tutorials
