### ISSUE TITLE
Not recieving followers

### ISSUE THREAD

**Issue by sm81008** [asimptot/FollowerBot#50]
@asimptot I ran the program and it says it giving me followers but I am not getting them. I tried using a vpn and used the bot on different accounts but it didn't work.

**Comment by rasky71** [comment]
I run the program and it worked for me, turn off the computer for a few hours and turn it on again, run the program, it tells me that I am getting followers but I am not getting them on instagram

**Comment by sm81008** [comment]
@rasky71 so its working for you after you restart computer?

**Comment by rasky71** [comment]
nope, it's not working for me

**Comment by sm81008** [comment]
oh dang

**Comment by sm81008** [comment]
@rasky71 it might be working now check it

**Comment by activeaqi** [comment]
I am the youtube page people complaining not getting the followers. I don't know the reason yet because I haven't reached there, caught up on early errors and posted in a next threads to you in "Errors on execution #51" and the link is https://github.com/asimptot/FollowerBot/issues/51

**Comment by asimptot** [comment]
Hi all,

I think there is a problem in server side. The server address is https://tolinay.com/instagram-takipci-hilesi . You can try to gain followers manually. If it doesn't work, I cannot do anything on my side. Because this script automatise user actions in this web page.

**Comment by sm81008** [comment]
@asimptot alright bro thank you
