### ISSUE TITLE
Errors on execution

### ISSUE THREAD

**Issue by activeaqi** [asimptot/FollowerBot#51]
Hello,

I've downloaded the code and installed all the necessary modules. I run it and enter username of Instagram it's giving a lot of errors. I am trying since 2 days but unable to fix them. I took 4 screenshot and clearly mentioned everything I know. Please help me fix those issues. 

https://ibb.co/rfjqsvt
https://ibb.co/t3KqSmS
https://ibb.co/9sB4SBh
https://ibb.co/Qj0r5y5

Thank you

**Comment by asimptot** [comment]
Please apply this solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by activeaqi** [comment]
Thank you for your quick response!
I'll do that and let you know

**Comment by activeaqi** [comment]
I've updating the following and I hope I am near.

Detailed Screenshot added here please see the link.
https://ibb.co/pQcPBML

Thank You

**Comment by asimptot** [comment]
You should add TABs. Otherwise Python is not able to run the code in your setup.

**Comment by activeaqi** [comment]
I've fixed the hierarchy of init file and the results are in the screenshot. 

Please see this screenshot and let me know what is preventing it from running
https://postimg.cc/8jT2x4Pw 

Thank you!

**Comment by asimptot** [comment]
You should install selenium library. Otherwise, it doesn't work.

**Comment by activeaqi** [comment]
Thank You so much for your help sir!
It worked for me!

**Comment by asimptot** [comment]
Good to hear that, enjoy!
