### ISSUE TITLE
 AddmeFast. problem 

### ISSUE THREAD

**Issue by arham837** [asimptot/FollowerBot#54]
Logged in AddmeFast. Your current point is: 12
Traceback (most recent call last):
File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 960, in
amf.login_facebook()
File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 72, in login_facebook
cookies = WebDriverWait(self.browser, 10).until(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
(No symbol) [0x00D837D3]
(No symbol) [0x00D18B81]
(No symbol) [0x00C1B36D]
(No symbol) [0x00C4D382]
(No symbol) [0x00C4D4BB]
(No symbol) [0x00C83302]
(No symbol) [0x00C6B464]
(No symbol) [0x00C81215]
(No symbol) [0x00C6B216]
(No symbol) [0x00C40D97]
(No symbol) [0x00C4253D]
GetHandleVerifier [0x00FFABF2+2510930]
GetHandleVerifier [0x01028EC1+2700065]
GetHandleVerifier [0x0102C86C+2714828]
GetHandleVerifier [0x00E33480+645344]
(No symbol) [0x00D20FD2]
(No symbol) [0x00D26C68]
(No symbol) [0x00D26D4B]
(No symbol) [0x00D30D6B]
BaseThreadInitThunk [0x75EC7D69+25]
RtlInitializeExceptionChain [0x772CBB9B+107]
RtlClearBits [0x772CBB1F+191]

**Comment by asimptot** [comment]
Are you sure that you entered your credentials correct? If yes, could you run the code in non headless mode, please? Then share your screen as screenshot.

**Comment by arham837** [comment]
Yes credential are correct as addme fast points are showing can you tell me how shall i run in non headless ?

**Comment by asimptot** [comment]
You should add # char in front of chrome_options.add_argument('--headless') line.

**Comment by arham837** [comment]
As this error is showing 

https://ibb.co/tqqdX7z
https://ibb.co/55mHmmY
https://ibb.co/WndLp37

**Comment by asimptot** [comment]
But I don't see your browser. You've just shared the source code. Can you please share your browser ss? It seems your browser doesn't open FB cookies page. So it should be dependent on your local network.

**Comment by arham837** [comment]
Can i share you my add me fast file with id and password? it will be more convienient.

**Comment by asimptot** [comment]
No, FB will already show it in *** format. You'll probably get the error before login page.

**Comment by arham837** [comment]
So what i have to share tell me step by step i will share you.

**Comment by asimptot** [comment]
1) Modify the code in non headless mode.
2) Run the code.
3) Share your screen. If the browser is closed immediately, just tell me whether you see FB cookies page or not.

**Comment by arham837** [comment]
automation is not entering id password in browser browser is opening.

**Comment by asimptot** [comment]
Even Addmefast credentials? or just Facebook?

**Comment by arham837** [comment]
just facebook

**Comment by asimptot** [comment]
I wrote to you to see your screen. Please apply those steps.

https://github.com/asimptot/FollowerBot/issues/54#issuecomment-1436630538

**Comment by arham837** [comment]
I see Fb page but it closses imediately and give error as mentioned up.

**Comment by asimptot** [comment]
Do you see cookies web page on FB? If no, i'll update the code according to your setup.

**Comment by arham837** [comment]
no

**Comment by asimptot** [comment]
Please add # chars in front of those lines and start to run.

        cookies = WebDriverWait(self.browser, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, '_9xo5'))
        )
        cookies.click()
        sleep(5)

**Comment by arham837** [comment]
From which line i have to add?

**Comment by asimptot** [comment]
from 72nd to 76th.

https://github.com/asimptot/FollowerBot/blob/main/get_credit_on_AddMeFast.py

**Comment by arham837** [comment]
After opening this browser closes 
https://ibb.co/fYSCN0w

**Comment by asimptot** [comment]
Please share your sourcecode. You can blur FB ID and password.

**Comment by arham837** [comment]
source code is in photo 
https://ibb.co/yPzsYst

**Comment by asimptot** [comment]
If you don't comment out cookies lines, you'll get this issue. I shared the solution in https://github.com/asimptot/FollowerBot/issues/54#issuecomment-1436694356

**Comment by arham837** [comment]
i have added this now new issue see through it 
https://ibb.co/9c67LXk

**Comment by asimptot** [comment]
For Gmail issue, please check in the following link: https://github.com/asimptot/FollowerBot/issues/32#issuecomment-1382025935

**Comment by arham837** [comment]
Can i remove ok.ru login because this is not opening in my country

**Comment by arham837** [comment]
how to remove tell me ?

**Comment by asimptot** [comment]
I'm not Python instructor. So I just help you fix errors in this repository. You can delete the task whatever you like.

---find this line---

array = [amf.surf_website, amf.youtube_view, amf.twitter_like, amf.twitter_retweet, amf.twitter_follow,
         amf.twitter_tweets, amf.instagram_like, amf.instagram_follow, amf.facebook_followers, 
         amf.facebook_share, amf.facebook_post_like, amf.facebook_post_share, amf.reddit_members, amf.reddit_upvotes,
         amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers, amf.reverbnation_fan, amf.okru_join]

---do this for your request---

array = [amf.surf_website, amf.youtube_view, amf.twitter_like, amf.twitter_retweet, amf.twitter_follow,
         amf.twitter_tweets, amf.instagram_like, amf.instagram_follow, amf.facebook_followers, 
         amf.facebook_share, amf.facebook_post_like, amf.facebook_post_share, amf.reddit_members, amf.reddit_upvotes,
         amf.youtube_subscribe, amf.pinterest_save, amf.pinterest_followers, amf.reverbnation_fan]

**Comment by arham837** [comment]
No problem bro thanks for you help please help me free followers as i am getting error

**Comment by arham837** [comment]
As i have open in headless mode browser opens and them imediatiely closes

**Comment by asimptot** [comment]
Can you open a new ticket? please close this one. Because this one is about Addmefast.

**Comment by arham837** [comment]
ok thanks
