### ISSUE TITLE
Not working and getting error after giving username

### ISSUE THREAD

**Issue by ajju2smart** [asimptot/FollowerBot#55]
Hey Developer, Thanks for this.

But i need you help in running the code in my side. When i execute the code "get_instagram_followers" or others as well then i'm getting below error
"Getting followers... Please do not terminate the program.
An error has been occurred. Retrying..."

Can you please help

**Comment by oskarfranz** [comment]
You could try digging into the website and checking the path of the elements that the script simulates is using. In my case my laptop viewport it's smaller and the path of the elements had to be corrected for the following ones:

 uid = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[1]/form/div/div[0]/input')
        uid.send_keys(username)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[1]/form/div/div[2]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[1]/div[0]/div/div/div[0]/div'))


Hope it helps!

**Comment by asimptot** [comment]
Thanks @oskarfranz !

@ajju2smart hi,

Does it work?

**Comment by ajju2smart** [comment]
> Thanks @oskarfranz !
> 
> @ajju2smart hi,
> 
> Does it work?

This module did not work for me so I have switched to a different module.

**Comment by asimptot** [comment]
After you switched, does it work on your local?

**Comment by ajju2smart** [comment]
I started with InstaPy/Followbot/ and it also has many issue and none is helping out as a community, so i started with own modules and I'm working on it.
