### ISSUE TITLE
An error has been occurred. Retrying...

### ISSUE THREAD

**Issue by JustLele78** [asimptot/FollowerBot#58]
Hi, i have this error, can you help me pls?
![errorr](https://user-images.githubusercontent.com/86966093/220044998-b21f489d-d7ba-4dcc-9a34-2431b3afbfb2.PNG)

**Comment by asimptot** [comment]
Please apply this solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by JustLele78** [comment]
Hi, i replaced this code, but he give me the same error

**Comment by asimptot** [comment]
Can you run the code in non headless mode, please?

**Comment by JustLele78** [comment]
yes now i try

**Comment by JustLele78** [comment]
I tried, it gives me the same error, the browser opens with the site, but it closes immediately

**Comment by asimptot** [comment]
Please update your code as the following. Then share your error messages.

from time import sleep
import sys
sys.path.append(r'C:\\Projects\\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        uid = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[1]/input')
        uid.send_keys(post_link)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[3]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0
    
    while(True):
        ig.go_to_website()
        i = i + 1

    j = j + 1

**Comment by JustLele78** [comment]
I changed the code with the one you sent me, but now it gives me this error:
![error 2](https://user-images.githubusercontent.com/86966093/220068466-bae88c4f-cd6e-4ea7-a5ec-4eadb872bb52.PNG)

The Code:
`from time import sleep
import sys
sys.path.append(r'C:\Projects\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        uid = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[1]/input')
        uid.send_keys(post_link)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[3]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0

    while(True):
        ig.go_to_website()
        i = i + 1

j = j + 1`

**Comment by asimptot** [comment]
1) Please copy the previous code.
2) Copy 

        N = 6
        actions = ActionChains(self.browser)
        for _ in range(N):
            actions.send_keys(Keys.TAB).perform()
            sleep(2)

        actions.send_keys(post_link).perform()

 instead of

        uid = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[1]/input')
        uid.send_keys(post_link)

**Comment by JustLele78** [comment]
it always gives me the same error :(
![error 3](https://user-images.githubusercontent.com/86966093/220072079-1e22c182-e8fc-4fe6-a9d5-c58e7c0ceff3.PNG)

**Comment by asimptot** [comment]
Can you send your source code please?

* get_instagram_likes.py
* init.py

**Comment by JustLele78** [comment]
get_instagram_likes.py:

`
from time import sleep
import sys
sys.path.append(r'C:\Projects\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        N = 6
        actions = ActionChains(self.browser)
        for _ in range(N):
            actions.send_keys(Keys.TAB).perform()
            sleep(2)

        actions.send_keys(post_link).perform()
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[3]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0

    while(True):
        ig.go_to_website()
        i = i + 1

j = j + 1
`
init.py:
`
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class Setup:
    def init(self):
        warnings.filterwarnings("ignore")
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--window-size=1036, 674')
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option('useAutomationExtension', False)
        #chrome_options.add_argument('--headless')
        chrome_options.add_argument("--log-level=3")
        chrome_options.add_experimental_option("prefs", {
        "profile.default_content_setting_values.notifications": 1
        })
        self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )

    def close_browser(self):
        self.browser.close()
`

**Comment by JustLele78** [comment]
get_instagram_likes.py

`from time import sleep
import sys
sys.path.append(r'C:\Projects\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        N = 6
        actions = ActionChains(self.browser)
        for _ in range(N):
            actions.send_keys(Keys.TAB).perform()
            sleep(2)

        actions.send_keys(post_link).perform()
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[3]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0

    while(True):
        ig.go_to_website()
        i = i + 1

j = j + 1`

**Comment by JustLele78** [comment]
init.py
`from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class Setup:
    def init(self):
        warnings.filterwarnings("ignore")
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--window-size=1036, 674')
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option('useAutomationExtension', False)
        #chrome_options.add_argument('--headless')
        chrome_options.add_argument("--log-level=3")
        chrome_options.add_experimental_option("prefs", {
        "profile.default_content_setting_values.notifications": 1
        })
        self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )

    def close_browser(self):
        self.browser.close()`

**Comment by asimptot** [comment]
Hi,

Why don't you use TABs? If you don't use, Python code doesn't work!

**Comment by JustLele78** [comment]
I know, I use them, when I paste them here they are removed

**Comment by JustLele78** [comment]
see the screenshots:
![init](https://user-images.githubusercontent.com/86966093/220074794-971a0aed-cae1-48e0-a688-4232db9d517f.PNG)
![1](https://user-images.githubusercontent.com/86966093/220074835-cfd948b8-d342-45ee-bc84-f4805114c5a2.PNG)
![2](https://user-images.githubusercontent.com/86966093/220074851-28bc1a07-411a-4ed1-82e4-28e962fe0e84.PNG)

**Comment by asimptot** [comment]
Hi,

Please update your code as the following.




from time import sleep
import sys
sys.path.append(r'C:\Projects\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        N = 6
        actions = ActionChains(self.browser)
        for _ in range(N):
            actions.send_keys(Keys.TAB).perform()
            sleep(2)

        actions.send_keys(post_link).perform()
        sleep(2)

        actions.send_keys(Keys.RETURN).perform()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)
ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0

    while(True):
        ig.go_to_website()
        i = i + 1
    j = j + 1

**Comment by JustLele78** [comment]
now it works, but only for the first time, then it stops there
![error 4](https://user-images.githubusercontent.com/86966093/220080076-ed829398-f06b-430b-a545-272d1be82c95.PNG)

**Comment by asimptot** [comment]
Please copy lines after 

element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
    WebDriverWait(self.browser, 1000).until(element_present)

from the repository. It will run infinitely.

**Comment by JustLele78** [comment]
do i have to copy them at the end of the code?

**Comment by asimptot** [comment]
yes, from this line to the end of the code.

**Comment by JustLele78** [comment]
like this?
![Capturess](https://user-images.githubusercontent.com/86966093/220081852-47b221ad-438a-4e23-baeb-ec8fb52c5107.PNG)

**Comment by asimptot** [comment]
No, please copy from the repo.

**Comment by JustLele78** [comment]
I did not understand, where should i copy it?

**Comment by JustLele78** [comment]
where is the repo?

**Comment by asimptot** [comment]
The repo is https://github.com/asimptot/FollowerBot/blob/main/get_instagram_likes.py

**Comment by JustLele78** [comment]
okay can you give me an example of where it should be pasted please?

this is my code
`from time import sleep
import sys
sys.path.append(r'C:\Projects\Get_Free_Followers')
from init import *

post_link = input('What is your post link?\n')
print('Getting likes... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)
    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-begeni-hilesi')
        sleep(4)

        N = 6
        actions = ActionChains(self.browser)
        for _ in range(N):
            actions.send_keys(Keys.TAB).perform()
            sleep(2)

        actions.send_keys(post_link).perform()
        sleep(2)

        actions.send_keys(Keys.RETURN).perform()

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\nYou got 10 likes!")
            self.browser.save_screenshot('liked.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

def close_browser(self):
    Setup.close_browser(self)

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0

    while(True):
        ig.go_to_website()
        i = i + 1
    j = j + 1`

**Comment by JustLele78** [comment]
I can't figure out where I should paste the line

**Comment by asimptot** [comment]
Please share an image of your code. Because I saw a few problems while you're copying the code.

**Comment by JustLele78** [comment]
sure
![code 1](https://user-images.githubusercontent.com/86966093/220098440-4ee60a08-041d-440c-8f5c-529992a0a24b.PNG)
![code 2](https://user-images.githubusercontent.com/86966093/220098464-e13bc569-3615-4c97-ab05-1e8ef80d08f6.PNG)

**Comment by asimptot** [comment]
Please obey TAB standarts. I see wrong lines in 38th line.

**Comment by JustLele78** [comment]
yes sorry, I fixed it

**Comment by JustLele78** [comment]
now what should i add?

**Comment by asimptot** [comment]
I don't see your code. Please share it again.

**Comment by JustLele78** [comment]
![code 1](https://user-images.githubusercontent.com/86966093/220100001-6a25996b-b7d1-40b6-820c-4c6883e3c051.PNG)
![code 2](https://user-images.githubusercontent.com/86966093/220100009-4b85dcc2-03e1-4fe2-bed8-f44f5a9d8cf8.PNG)

**Comment by JustLele78** [comment]
![code 1 fixed](https://user-images.githubusercontent.com/86966093/220100255-6d562a82-21fc-4514-82be-99245d3cd440.PNG)
![code 2 fixed](https://user-images.githubusercontent.com/86966093/220100266-21aa331a-45ee-466c-8e1d-c223d20c5b3d.PNG)

**Comment by asimptot** [comment]
Why do you have 2 close_browser function? Please remove one of them. You should update in the following part.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/18220180/220100821-ee27e351-57d3-4994-b4d2-4d966e677d5d.png">

**Comment by JustLele78** [comment]
![replaced](https://user-images.githubusercontent.com/86966093/220102259-d1768424-2298-45e5-af6b-f031255b9338.PNG)

**Comment by JustLele78** [comment]
i added the code

**Comment by asimptot** [comment]
Please add this code block to 27th line.

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

**Comment by JustLele78** [comment]
yes I started it, it works but after the first one it doesn't restart automatically
![error bho](https://user-images.githubusercontent.com/86966093/220111352-d1be2778-b89c-4a9b-bc84-e9d9b179853c.PNG)

**Comment by asimptot** [comment]
It seems no problem. You should wait almost 1000 second for next process. Did you wait 1000 seconds for it?

**Comment by JustLele78** [comment]
yes and after I waited, it gives me this error and it reopens
![usdasdc](https://user-images.githubusercontent.com/86966093/220117971-7c64b5c9-cb6c-469f-81c2-f2c4731bbee3.PNG)

**Comment by asimptot** [comment]
Strange! Can you set a higher value than 1000 seconds?

**Comment by JustLele78** [comment]
yes, I try

**Comment by BenjamindeG28** [comment]
> 

I Also rewrote the init.py but it now gives an error: 

Traceback (most recent call last):
  File "C:\Users\groot\OneDrive\BètaBijles\FollowerBot-main\get_instagram_followers.py", line 4, in <module>
    from init import *
  File "C:\Users\groot\OneDrive\BètaBijles\FollowerBot-main\init.py", line 22, in <module>
    self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )
                                                                                             ^^^^^^^^^^^^^^
NameError: name 'chrome_options' is not defined
