### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Abohmd** [asimptot/FollowerBot#6]
how to use in cmd pls

**Comment by asimptot** [comment]
1) Create a folder under C:// as Projects --> Get_Free_Followers
2) Go to this path writing 'cd C:\Projects\Get_Free_Followers' command on CMD.
3) write 'python get_free_followers.py' and press enter.

**Comment by Abohmd** [comment]
can't open file 'E:\\برامج\\FollowerBot-main\\FollowerBot-main\\get_free_followers.py': [Errno 2] No such file or directory

fix?

**Comment by Abohmd** [comment]
![image](https://user-images.githubusercontent.com/109475323/197196744-2fd28569-7b01-495a-92bb-c6f4ce4f7800.png)

**Comment by Abohmd** [comment]
![image](https://user-images.githubusercontent.com/109475323/197197693-950baeec-bb58-4d41-933f-9c39d1735d02.png)

**Comment by asimptot** [comment]
It seems you didn't install Python. Please try to install and run again.
