### ISSUE TITLE
error kingdomlikes

### ISSUE THREAD

**Issue by lepojevicdanilo** [asimptot/FollowerBot#60]
Traceback (most recent call last):
  File "c:\Users\danil\Downloads\FollowerBot-main\get_credit_on_KingdomLikes.py", line 4, in <module>
    from init import *
  File "c:\Users\danil\Downloads\FollowerBot-main\init.py", line 12
    warnings.filterwarnings("ignore")
    ^
IndentationError: expected an indented block after function definition on line 11
PS C:\Users\danil\Downloads\FollowerBot-main> 
![Screenshot_14](https://user-images.githubusercontent.com/90660734/220226583-85e3253e-221c-4af7-b729-81febbcb0c2b.png)

**Comment by asimptot** [comment]
Hi,

Did you open Get_Free_Followers folder under C://Projects ? If no, you should edit 4th line.

**Comment by lepojevicdanilo** [comment]
what i need to put in 4th line??

**Comment by asimptot** [comment]
Your absolute path

**Comment by lepojevicdanilo** [comment]
I created folders projects and get free followers, but what should I do next I can't find get_free_followers.py

**Comment by lepojevicdanilo** [comment]
can you write a little more broadly?
