### ISSUE TITLE
An error has been occurred. Retrying...

### ISSUE THREAD

**Issue by lepojevicdanilo** [asimptot/FollowerBot#62]
i getting this error 

![Screenshot_15](https://user-images.githubusercontent.com/90660734/220391113-da79db5e-52a4-4f1d-abf9-e87918eef9d4.png)

**Comment by asimptot** [comment]
Can you give more details, please? Which program do you use?

**Comment by lepojevicdanilo** [comment]
visual studio code, 

from time import sleep
import sys
sys.path.append(r'C:\\Projects\\Get_Free_Followers')
from init import *
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

username = input('What is your Instagram username?\n')
print('Getting followers... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-takipci-hilesi')
        sleep(4)

        uid = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[1]/input')
        uid.send_keys(username)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/form/div/div[3]/button')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[2]/div[2]/div[1]/div/div/div[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\n10 followers followed you!")
            self.browser.save_screenshot('followed.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0
    try:
        while(True):
            try:
                ig.go_to_website()
                i = i + 1
            except:
                ig.close_browser()
        j = j + 1
    except:
        print('An error has been occurred. Retrying...')

**Comment by asimptot** [comment]
Did you check the FAQ? 

https://github.com/asimptot/FollowerBot/issues/57#issuecomment-1436601554

**Comment by jjharoll** [comment]
I had the same error and with that faq replacing the code by 
the file: get_instagram_followers.py

from time import sleep
import sys
sys.path.append(r'C:\\Projects\\Get_Free_Followers')
from init import *
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

username = input('What is your Instagram username?\n')
print('Getting followers... Please do not terminate the program.')

class Instagram:
    def setup(self):
        Setup.init(self)

    def go_to_website(self):
        sleep(4)
        self.browser.get('https://tolinay.com/instagram-takipci-hilesi')
        sleep(4)
        uid = self.browser.find_element(By.XPATH, '/html[1]/body[1]/div[3]/div[2]/div[2]/form[1]/div[1]/div[1]/input[1]')   
        uid.send_keys(username)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html[1]/body[1]/div[3]/div[2]/div[2]/form[1]/div[1]/div[3]/button[1]')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[3]/div[2]/div[2]/div/div/a[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)

        if("Başarıyla Gönderildi" in self.browser.page_source):
            print(f"\n10 followers followed you!")
            self.browser.save_screenshot('followed.png')
        elif("Çok Hızlı İşlem Yapıyorsunuz" in self.browser.page_source):
            print(f"\nError! Do not run the program fast mode!")
            self.browser.save_screenshot('error.png')
        else:
            print(f"\nError! Your credits have been expired! Please change your Instagram username.")
            self.browser.save_screenshot('error.png')

    def close_browser(self):
        Setup.close_browser(self)

ig = Instagram()
j = 0
while(True):
    ig.setup()
    i = 0
    try:
        while(True):
            try:
                ig.go_to_website()
                i = i + 1
            except:
                ig.close_browser()
        j = j + 1
    except:
        print('An error has been occurred. Retrying...')

**Comment by asimptot** [comment]
Can you share your error and code as screenshot format? Because I can't see them well due to tab format problem.

**Comment by adas71** [comment]
I have the same error bro.. We chat via email..

**Comment by adas71** [comment]
![Snímek obrazovky (28)](https://user-images.githubusercontent.com/86240077/220926097-3dbe0154-676a-4125-98f8-5a891238d1d4.png)

**Comment by asimptot** [comment]
@adas71 hi,

Can you send your code's screenshot, please? Btw, can you also run it in non headless mode?

**Comment by adas71** [comment]
![Snímek obrazovky (29)](https://user-images.githubusercontent.com/86240077/220959673-b089f422-db35-4185-9368-52f32b483851.png)

**Comment by adas71** [comment]
How to do non headless mode ?

**Comment by asimptot** [comment]
Please add # character to 18th line in this code: https://github.com/asimptot/FollowerBot/blob/main/init.py

**Comment by asimptot** [comment]
Hi all,

Please use the latest code. I've updated it.

https://github.com/asimptot/FollowerBot/commit/5127ba1c5fa17173a54d961737cb13bdfb221f6f

**Comment by adas71** [comment]
@asimptot Bro i fix it with followers but i have problems with likes.. :D

**Comment by asimptot** [comment]
Can you send your problem's screenshot please?

**Comment by asimptot** [comment]
See the https://github.com/asimptot/FollowerBot/issues/63
