### ISSUE TITLE
İnstagram Takipçi Gönderme Çalışmıyor

### ISSUE THREAD

**Issue by h3kdev** [asimptot/FollowerBot#64]
**Maalesef takipçi gönderme kodu başarılı bir şekilde çalışmıyor.**

**Comment by asimptot** [comment]
Hello,

Can you send your error code as a screenshot, please?

**Comment by h3kdev** [comment]
"An error has been occurred. Retrying..." hatası alıyorum.

**Comment by asimptot** [comment]
Did you use the latest code? If so, please run it in non headless mode.

**Comment by h3kdev** [comment]
Evet en son paylaştığın kodu kullandım. Başsız olmayan mod nedir?

**Comment by asimptot** [comment]
No, I don't. Please see the following comment: https://github.com/asimptot/FollowerBot/issues/62#issuecomment-1442190940

**Comment by h3kdev** [comment]
Abi headless mode ne, eğer pencere açması lazımsa hayır açmıyor. Lütfen türkçe cevap verir misin anlayamıyorum :D

**Comment by asimptot** [comment]
Ustte bildirdigim yorumdaki satiri # ile yorum satirina alip calistiralim. Boylelikle tarayicinin nasil davrandigini gorebilecegim.

**Comment by h3kdev** [comment]
Senin kullandığın site bozuk ya :D

**Comment by asimptot** [comment]
Ben sadece adimlari otomatiklestirdim. Siteye girip kullanici adini yazdiginda takipci gelmiyorsa site kaynaklidir. Benim yapabilecegim pek bir sey yok :)

**Comment by h3kdev** [comment]
peki sağol abi bunun gibi başka site var mı bildiğin?

**Comment by asimptot** [comment]
Diger paylastigim .py dosyalari kredi sistemiyle calisiyor. Iclerinde en populeri addmefast. Tolinay gibi çalışan pek site bulamadim acikcasi. Bulursan haberim olsun, otomatize edeyim :)

**Comment by h3kdev** [comment]
Teşekkürler yazarım tabii ki. Kolay gelsin <3

**Comment by asimptot** [comment]
@h3kdev selam,

Tekrar deneyebilir misin? Kodu da guncelledim.

**Comment by h3kdev** [comment]
Müsait bir zamanda deneyip döneceğim

**Comment by h3kdev** [comment]
E-postayı random bir tane mi gireceğiz yoksa takipçi atacağımız hesabın e-posta bilgilerini mi?

**Comment by asimptot** [comment]
yok hayir, fake bir tane gmail hesabi olusturabilirsin. Sitenin sahibi botlara karsi onlem almis gorunuyor. Takip olayiyla hic alakasi yok aslinda gmail login isleminin. Sembolik olarak yapacagiz bunu.

**Comment by h3kdev** [comment]
**10 followers followed you!** 

diyor ancak hesaba takipçi gelmiyor.

**Comment by asimptot** [comment]
tolinay.com/instagram-takipci-hilesi bu siteye girip kullanici adini yazip deneyebilir misin? Site uzerinden geliyorsa yazdigim programla gelmiyorsa benim tarafimda sorun var demek. Cozmeye calisayim.
