### ISSUE TITLE
Bots not following

### ISSUE THREAD

**Issue by Mafiosoweb1** [asimptot/FollowerBot#67]
Hi, so I've got it running again, it does say that it added followers but nobody followes. I've tried different accounts and VPN but nothing worked, any idea what could it be? Does it work for you?
![Snímek obrazovky 2023-03-02 001523](https://user-images.githubusercontent.com/69605438/222288727-2c4feb99-7ec3-4355-8718-93568a8d28b0.png)

**Comment by asimptot** [comment]
I have no clue on server side. Maybe you can try to boost a few days later.
