### ISSUE TITLE
Trying to use the code on another username but it doesn't work.

### ISSUE THREAD

**Issue by Kyle-TT** [asimptot/FollowerBot#68]
So I updated the code to the newest iteration updated and I tried to use it on a username for another account but it doesn't work.

I used the code previously on a different username even after updating I tested it on both usernames and I got an increase on follower count on the username that doesnt have any issues but no follower increase on the username that is having the issue.

**Comment by asimptot** [comment]
Hello,

Sorry but i didn't get what you meant. Do you mean it was worked before i updated the code?

**Comment by Kyle-TT** [comment]
I've tried redownloading the entire zip file to ensure theres no corruption on my side and i've checked the username and it is correct to the account. 

As well as ive let the code run for up to a full day and still i am getting no results.

Honestly I am just entirely confused.

**Comment by asimptot** [comment]
Good question. Did you try to use different Gmail address? I'm not familiar with this topic due to server side, but just try to log in with different Gmail account.

**Comment by Kyle-TT** [comment]
So i changed the gmail address and still nothing. Tried to change the username of the account and still nothing.

**Comment by Mafiosoweb1** [comment]
Hi I had the same problem, I have tried many VPNs till I find some that do work. Just go ahead and find one that isn't banned, then it should work normally.

**Comment by asimptot** [comment]
@Mafiosoweb1 hi,

Can you give more details your steps how to succeed for others, please? What did you find? Is it Gmail address or Instagram username that isn't banned? Does the result change according to VPN? Is there any credit restriction gainin followers/likes?

**Comment by Kyle-TT** [comment]
> @Mafiosoweb1 hi,
> 
> Can you give more details your steps how to succeed for others, please? What did you find? Is it Gmail address or Instagram username that isn't banned? Does the result change according to VPN? Is there any credit restriction gainin followers/likes?

Yeah what this guy said
