### ISSUE TITLE
What About The API ?

### ISSUE THREAD

**Issue by activeaqi** [asimptot/FollowerBot#69]
I've tried this after few days and now the API is not working, can you help ?

**Comment by asimptot** [comment]
What is API? Can you give more details, please?

**Comment by activeaqi** [comment]
I've update the pip just incase.
I've changed nothing my account was blocked and afterwards I haven't used this code, I am working on the new account and I am getting these errors.

**Comment by asimptot** [comment]
Hello,

What do you mean that your account was blocked? This script provides activities, automatically.

**Comment by activeaqi** [comment]
> What do you mean that your account was blocked?

The Instagram account was blocked that could be because It was very new and I've start getting a lot of follower rapidly but that's beside the point.

Can you help me fix the error above ? I am unable to run the code anymore.

**Comment by asimptot** [comment]
Please share your code as a screenshot

**Comment by activeaqi** [comment]
This the code screenshots

https://i.postimg.cc/Hkj76XD6/7.png
https://i.postimg.cc/pdF5Hvd8/8.png
https://i.postimg.cc/tTGZRc1c/9.png

**Comment by activeaqi** [comment]
Video of what happen when I run the code

https://drive.google.com/file/d/1xlRVbu43W2etvwhsU_-j-8Nu7YzJLPmE/view?usp=share_link

**Comment by asimptot** [comment]
Well, can you run it in non-headless mode to see what it happened?

**Comment by activeaqi** [comment]
> non-headless mode

Please elaborate further, I am a very basic programmer barely make things working so I need help of what you said above "non-headless mode"

**Comment by activeaqi** [comment]
Thank you for all your efforts and hard work!

**Comment by asimptot** [comment]
Please add # in front of 17th line in init.py file and re-run the program.

**Comment by activeaqi** [comment]
Please see this video it's in non-headless mode

https://drive.google.com/file/d/1gQjFlCZcYQ_LR-zRkr9mMUa-vE30bhXB/view?usp=share_link

**Comment by asimptot** [comment]
thanks for the video. Why don't you use the latest code? Those lines are different in your code. Please check it and update from the system.

uid = self.browser.find_element(By.XPATH, '/html/body/div[3]/div[2]/div[2]/form/div/div[1]/input')
button = self.browser.find_element(By.XPATH, '/html/body/div[3]/div[2]/div[2]/form/div/div[3]/button')

**Comment by activeaqi** [comment]
I am sorry I did noticed the code has changed, I hardly found it I was finding your video but I couldn't, later I found in telegram your youtube channel is deleted, so sorry to hear this.
I hardly found this code because I had many of your video links saved with.

I'll download the latest code!
Thank you!

**Comment by asimptot** [comment]
To be honest, I have no YT channel :) good to hear that you've fixed on your end!
