### ISSUE TITLE
Unusuall Error Message

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#7]
The script works, I see the activities within the website and I earn points for YT views, I saw this particular error after running script for almost 24 hours , though it is not affecting the script in earning points. Please see the below:

![image](https://user-images.githubusercontent.com/85780689/197458471-77ff2f9c-3118-41a8-bca9-dc0fd329afe4.png)

**Comment by asimptot** [comment]
If it doesn't affect to earn points, you can ignore and skip this error message.

**Comment by saabtech** [comment]
I am getting this error now: 

![image](https://user-images.githubusercontent.com/85780689/198024311-d4e6b759-5c63-4201-9fe0-1bf2c4043c2a.png)
