### ISSUE TITLE
error when i put in instagram followers

### ISSUE THREAD

**Issue by sm81008** [asimptot/FollowerBot#70]
![image](https://user-images.githubusercontent.com/122185219/224566052-28b33cf9-2246-4f9b-9ab4-9cfd0530e67b.png)

**Comment by asimptot** [comment]
Please check tabs. Otherwise Python doesn't allow to run your code.

**Comment by sm81008** [comment]
@asimptot what do you mean?

**Comment by asimptot** [comment]
please check your code and give a space(TAB) in front of your lines.

**Comment by AFOUNDX** [comment]
i have the same issue, but i don't understand you. like can u explain step by step?

**Comment by asimptot** [comment]
If you don't use TAB(space), Python doesn't allow to run your code. I cannot help you on this.

https://peps.python.org/pep-0008/#tabs-or-spaces
