### ISSUE TITLE
Chromedriver issues

### ISSUE THREAD

**Issue by AFOUNDX** [asimptot/FollowerBot#71]
can you explain in detail how do i fix this
![Screenshot (33)](https://user-images.githubusercontent.com/91894691/230842536-aa5f921c-adf1-4058-935f-59dc4a091173.png)

**Comment by asimptot** [comment]
Can you please update in the following line in init.py file?

self.browser = uc.Chrome(options=chrome_options, version_main=110) --> self.browser = uc.Chrome(options=chrome_options, version_main=112)

**Comment by AFOUNDX** [comment]
> Can you please update in the following line in init.py file?
> 
> self.browser = uc.Chrome(options=chrome_options, version_main=110) --> self.browser = uc.Chrome(options=chrome_options, version_main=112)

where do i add/replace the line?
![Screenshot (34)](https://user-images.githubusercontent.com/91894691/230931601-6100bcac-a641-4a1a-aba3-51bbcce72fc7.png)

**Comment by asimptot** [comment]
Thank you for your kind words! I'm happy to help. There are many great Python courses available, depending on your skill level and specific interests. Here are a few popular options:

Python for Everybody - This is a great course for beginners and covers the basics of programming with Python. It's available for free on Coursera.

Complete Python Bootcamp: Go from zero to hero in Python 3 - This is a comprehensive course on Udemy that covers everything from the basics of Python to more advanced topics like web development and data analysis.

Python Crash Course: A Hands-On, Project-Based Introduction to Programming - This book by Eric Matthes is a great resource for beginners who want to learn Python through hands-on projects.

I hope this helps! Let me know if you have any other questions.
