### ISSUE TITLE
Chromedriver error

### ISSUE THREAD

**Issue by jvstlele** [asimptot/FollowerBot#77]
Hi, the bot presents me with this error, how can I solve it?
![error](https://github.com/asimptot/FollowerBot/assets/86966093/19392f7f-6cc6-4c3c-825a-dd945102b3e6)

**Comment by asimptot** [comment]
This is temporary known error.

1) Please download chromedriver 114.
2) Add the path to your init.py code.
3) Re-run it again. 

If you cannot do this, I'll write it for you.

**Comment by jvstlele** [comment]
Thank you, I will try to do that

**Comment by asimptot** [comment]
Generic fix:    https://github.com/asimptot/FollowerBot/blob/main/init.py
