### ISSUE TITLE
Update the code to older stable chromedriver version like 104 

### ISSUE THREAD

**Issue by MiChaelinzo** [asimptot/FollowerBot#79]
Can  you update the code to work in 114 Stable-Chromedriver or older version in 104 currently it only works in 112, I cannot find any resources/link where I can update into 112. I'm using Linux version 5.16.0-kali7-amd64 (devel@kali.org) (gcc-11 (Debian 11.2.0-19) 11.2.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01). Also can you update to make it work in Chronium too for raspberry pi?

**Comment by asimptot** [comment]
Hi,

To solve the problem in init.py, you can apply this temporary solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by MiChaelinzo** [comment]
I don't know how would this solve my problem unable to use the software because it still runs in 112, also the code you gave me have several errors: 

```
michael@home:~/ㄒㄖㄖㄥ丂/FollowerBot$ sudo python3 get_instagram_followers.py
Traceback (most recent call last):
  File "/home/michael/ㄒㄖㄖㄥ丂/FollowerBot/get_instagram_followers.py", line 3, in <module>
    from init import *
  File "/home/michael/ㄒㄖㄖㄥ丂/FollowerBot/init.py", line 11
    def init(self):
    ^
IndentationError: expected an indented block after class definition on line 10

```

**Comment by asimptot** [comment]
You should choose the correct chromedriver in this link:    https://chromedriver.chromium.org/downloads
Then show this file in your code.

**Comment by MiChaelinzo** [comment]
> You should choose the correct chromedriver in this link: https://chromedriver.chromium.org/downloads Then show this file in your code.

I did that #80

**Comment by MiChaelinzo** [comment]
Sorry I fix the indentation the code is working perfectly

**Comment by MiChaelinzo** [comment]
I fix the indentation got the code working but I got this error running it: 
Getting followers... Please do not terminate the program.
```

Traceback (most recent call last):
  File "/home/ㄒㄖㄖㄥ丂/FollowerBot/get_instagram_followers.py", line 66, in <module>
    ig.setup()
  File "/home/ㄒㄖㄖㄥ丂/FollowerBot/get_instagram_followers.py", line 10, in setup
    Setup.init(self)
  File "/home/ㄒㄖㄖㄥ丂/FollowerBot/init.py", line 23, in init
    self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55fcb7538403 <unknown>
#1 0x55fcb733e778 <unknown>
#2 0x55fcb7362fa9 <unknown>
#3 0x55fcb735e12b <unknown>
#4 0x55fcb739983a <unknown>
#5 0x55fcb73938f3 <unknown>
#6 0x55fcb73690d8 <unknown>
#7 0x55fcb736a205 <unknown>
#8 0x55fcb757fe3d <unknown>
#9 0x55fcb7582db6 <unknown>
#10 0x55fcb756913e <unknown>
#11 0x55fcb75839b5 <unknown>
#12 0x55fcb755d970 <unknown>
#13 0x55fcb75a0228 <unknown>
#14 0x55fcb75a03bf <unknown>
#15 0x55fcb75baabe <unknown>
#16 0x7f374a29684a <unknown>

```

**Comment by asimptot** [comment]
@MiChaelinzo hi,

I've just committed new changes to the repository. Could you use the latest code, please?

**Comment by MiChaelinzo** [comment]
same issue btw I got google-chrome --version 104 and chromedriver --version 112.0.5615.28

**Comment by asimptot** [comment]
Your chromedriver.exe version and your browser should have the same version. Can you adjust your chromedriver.exe according to your browser?

**Comment by MiChaelinzo** [comment]
I don't know how to do that etc. latest Google-chrome is 114 I cannot find 112 the latest I got for old browser is 104 I forgot 3rd party link I downloaded it from.

**Comment by asimptot** [comment]
https://chromedriver.chromium.org/downloads

Please use this link to download correct file according to your browser version. It seems you use incompatible file.

**Comment by MiChaelinzo** [comment]
What should I choose [ChromeDriver 112.0.5615.28] or [ChromeDriver 112.0.5615.49]

**Comment by asimptot** [comment]
Try what you want. I think the control is in the first digit that is 112.

**Comment by MiChaelinzo** [comment]
Btw I already have [ChromeDriver 112.0.5615.28] but where can we download the browser for 112?

**Comment by asimptot** [comment]
<img width="292" alt="Capture" src="https://github.com/asimptot/FollowerBot/assets/18220180/b4bace96-6658-4863-9be0-745d49bc06ac">
I use in the attached version. You can upgrade yours to them. Else, try another 112 version.

**Comment by MiChaelinzo** [comment]
I'll try to update my Google Chrome and get back to you! because I'm using Debian Kali Linux and it's very buggy currently even simple updates/upgrades mess up the system

**Comment by asimptot** [comment]
Generic fix:    https://github.com/asimptot/FollowerBot/blob/main/init.py
