### ISSUE TITLE
Suggestion: Script for Like4Like or AddmeFast

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#8]
The script for Youlikehits work great, the only drawback is we are having less members there, Is it possible to work on Like4Like and Addmefast since both has youtube view too and the members are very much active there. Currently I am using social media BOT for that to earn points, But script like yours can save lot of time.

**Comment by asimptot** [comment]
@saabtech hi,

Both websites include 'I am not human' verification. If you find alternative websites that don't include, I can work on this!

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> Both websites include 'I am not human' verification. If you find alternative websites that don't include, I can work on this!

Yes, They do have Human verification, Please find the below Websites and i checked couple of them without having verification. 

![image](https://user-images.githubusercontent.com/85780689/197694170-753d2b02-3e7d-4701-b57a-a254cba56220.png)

**Comment by asimptot** [comment]
@saabtech hi,

Those are very much! Could you prioritize, please?

**Comment by asimptot** [comment]
@saabtech  hi,

I have just committed here. You can start to run it!

**Comment by asimptot** [comment]
@saabtech hi,

I've just added for Likestool app. But the website doesn't allow to add Instagram username. Could you please check it on your side, as well?

**Comment by saabtech** [comment]
> @saabtech hi,
> 
> I've just added for Likestool app. But the website doesn't allow to add Instagram username. Could you please check it on your side, as well?

I will do it now and update you

**Comment by asimptot** [comment]
@saabtech hi,

Unfortunately, yes. Linkcollider is better, but it doesn't allow to surf more than 20 websites. So that youlikehits is still the best.
