### ISSUE TITLE
I just updated to 112 chromedriver but I got this error

### ISSUE THREAD

**Issue by MiChaelinzo** [asimptot/FollowerBot#80]
<img width="494" alt="Screenshot 2023-06-19 151211" src="https://github.com/asimptot/FollowerBot/assets/68110223/a0cac1a8-8c25-41f8-9b82-9de88c1054d4">

**Comment by MiChaelinzo** [comment]
my ChromeDriver is `112.0.5615.28 (e01c41304994a51cedfb5f0fac134687ba993bfb-refs/branch-heads/5615@{#494})
` as you can see below the snippet

**Comment by asimptot** [comment]
Please apply this temporary solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by asimptot** [comment]
Generic fix:    https://github.com/asimptot/FollowerBot/blob/main/init.py
