### ISSUE TITLE
Service int line 50 error

### ISSUE THREAD

**Issue by Rockdox** [asimptot/FollowerBot#81]
cannot access local variable 'service' where it is not associated with a value

**Comment by asimptot** [comment]
Can you send your error as a ss pls?

**Comment by jvstlele** [comment]
Is this, it gave me the same error
![Capture](https://github.com/asimptot/FollowerBot/assets/86966093/7ac90ee8-4b98-4b37-9889-9949099dbd7c)

**Comment by asimptot** [comment]
I've just fixed the problem. Can you use the latest init.py file?

**Comment by Rockdox** [comment]
> I've just fixed the problem. Can you use the latest init.py file?

![Capture](https://github.com/asimptot/FollowerBot/assets/114359988/141de842-a55c-468c-ae65-092eb5e5ff21)

Many errors

**Comment by asimptot** [comment]
You should download the chromedriver file and move to your Chrome path by yourself. Otherwise, it won't work fine!
