### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jvstlele** [asimptot/FollowerBot#82]
Hi, it gives me this error
![Capture](https://github.com/asimptot/FollowerBot/assets/86966093/f26d188d-c3cf-44a2-8daa-d297303ea722)

**Comment by jvstlele** [comment]
![2](https://github.com/asimptot/FollowerBot/assets/86966093/67b238c3-918e-4b93-ad39-006e4ddaca66)

**Comment by asimptot** [comment]
Please use the same versioned chromedriver and Chrome browser.

**Comment by asimptot** [comment]
Generic fix:    https://github.com/asimptot/FollowerBot/blob/main/init.py
