### ISSUE TITLE
Follower.py issue

### ISSUE THREAD

**Issue by stunna2k** [asimptot/FollowerBot#83]
This code pops up for 3 seconds then the whole cmd just goes away please help me.![Screenshot 2023-07-05 140955](https://github.com/asimptot/FollowerBot/assets/138619942/854920dd-052d-46cf-a134-00d141c91243)

**Comment by asimptot** [comment]
Hi, you should input your driver path like executable_path='C:/.../.../chromedriver.exe'

**Comment by stunna2k** [comment]
I dont understand, can u please guide me on how to do that?

**Comment by asimptot** [comment]
Please use the latest .py file. I think it will fix your problem.

https://github.com/asimptot/FollowerBot/blob/main/init.py

**Comment by asimptot** [comment]
You should install the library.

**Comment by stunna2k** [comment]
How do I install the library?

**Comment by stunna2k** [comment]
> Please use the latest .py file. I think it will fix your problem.
> 
> https://github.com/asimptot/FollowerBot/blob/main/init.py

It doesnt work, 
![image](https://github.com/asimptot/FollowerBot/assets/138619942/29705efa-7558-4954-af5f-a541e924ab1a)

**Comment by asimptot** [comment]
https://pypi.org/project/seleniumbase/1.15.3/

You can find the documentation how to install.

**Comment by stunna2k** [comment]
error 
![image](https://github.com/asimptot/FollowerBot/assets/138619942/9231cc13-28a7-4850-9521-c72ad0bfda8c)

**Comment by asimptot** [comment]
It seems you encountered an error while installing the library. You should follow the instructions.

https://pypi.org/project/seleniumbase/1.15.3/

**Comment by stunna2k** [comment]
Now it shows this, it just stops here..
![image](https://github.com/asimptot/FollowerBot/assets/138619942/c03c65dd-a58e-468a-9c2f-f81c86948643)

**Comment by stunna2k** [comment]
It works TY
