### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by jvstlele** [asimptot/FollowerBot#84]
Hi, it gives me this error and doesn't give me likes, do you know how I can solve it?
![error](https://github.com/asimptot/FollowerBot/assets/86966093/75f6d82c-a10a-438f-9d01-de894e0cf9b1)

**Comment by asimptot** [comment]
Can you run this code in non-headless mode and tell me what happened on your end?

**Comment by jvstlele** [comment]
can you show me how please?

**Comment by asimptot** [comment]
1) Go to https://github.com/asimptot/FollowerBot/blob/main/init.py.
2) Change self.browser = Driver(headless=True) line as self.browser = Driver(headless=False).
3) Run it again.

**Comment by jvstlele** [comment]
stops at this point in the
![error2](https://github.com/asimptot/FollowerBot/assets/86966093/748e0672-640d-4456-ab38-d76340606a4b)
 login and doesn't go any further
