### ISSUE TITLE
Problem in the execution of the program

### ISSUE THREAD

**Issue by Ghkkgff** [asimptot/FollowerBot#86]
Hi, 
I dont know if its a fault of mine or a error as i am very new in this field like a 3 days old 
Whenever i try the command like,
python get_credit_on_YouLikeHits.py
And
python add_instagram_likes.py

Its shows me that smthing like seleniumbase is missing
Idk wht is tht 
And it also show smthing else ill leave a ss

Thank you i hope you will reply!

[IMG_20230814_104250.jpg](https://github.com/asimptot/FollowerBot/assets/142087146/67adc8d4-d640-4ada-8fd6-ba1f3bfb6c4d)

**Comment by Ghkkgff** [comment]
Note - i Am using a application called termux in a android phone

**Comment by asimptot** [comment]
I'm unfamiliar with Termux. Is it an environment like Linux?
