### ISSUE TITLE
Can you help me please ?

### ISSUE THREAD

**Issue by adas71** [asimptot/FollowerBot#88]
IDK what kind of problem is this. 

Thx.

![image](https://github.com/asimptot/FollowerBot/assets/86240077/50dc37f9-596b-4a1d-b562-179fe23a61d3)

**Comment by asimptot** [comment]
Hi, you should install this library. Otherwise, you will keep getting this error.

pip install seleniumbase

**Comment by adas71** [comment]
thx.. sorry xd

**Comment by adas71** [comment]
solved
