### ISSUE TITLE
When I run get_kingdomlikes it does nothing.. :/

### ISSUE THREAD

**Issue by adas71** [asimptot/FollowerBot#89]
![image](https://github.com/asimptot/FollowerBot/assets/86240077/e791f516-6126-4f00-b8be-1e8b1dc76007)

**Comment by asimptot** [comment]
Hi, did you input your credentials into the code? To run KingdomLikes.py, you should have a valid account.

**Comment by adas71** [comment]
I did it before, but still not works

**Comment by asimptot** [comment]
Can you share the error detail with me(e.g. screenshot)?

**Comment by adas71** [comment]
It won't show any error there.. it won't show anything at all as I sent in the attachment.. It shows only this.. 

![image](https://github.com/asimptot/FollowerBot/assets/86240077/ccf91c2e-54c9-4a37-9a7b-cd174b77bee8)

**Comment by asimptot** [comment]
Please ensure that your libraries have been installed properly and Python configurations have been fine. It seems this problem is not related to the code.

**Comment by adas71** [comment]
I reinstalled python and install all requirements.. :/ so idk.. and the problem still persists..

**Comment by adas71** [comment]
Do you have any advice for me ?

**Comment by asimptot** [comment]
First of all, I must see the problem. This image includes nothing regarding the error: 
![image](https://github.com/asimptot/FollowerBot/assets/18220180/5f9c0f68-fcd7-4465-86d1-2351f5d611c4)
