### ISSUE TITLE
Error on Youlikehits script

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#9]
The error just started appearing today morning after a long run of the scrip: tried to restart the script but i get the below error:
![image](https://user-images.githubusercontent.com/85780689/198024611-2a68dc4a-793e-4c01-b38a-7c8a3a62c19d.png)

I will update the chrome and see if there is the script work without above error.

**Comment by saabtech** [comment]
After chrome update, the script works now.

**Comment by asimptot** [comment]
According to last comment, I close the issue.
